# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: bhildebr <bhildebr@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/02/15 13:46:55 by bhildebr          #+#    #+#              #
#    Updated: 2024/02/15 19:51:54 by bhildebr         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# This Makefile was automatically generated by Trillian.
# See the source code to learn more.

NAME = libtrillian.a
RELEASE_NAME = trillian
RELEASE_VERSION = 0.0.0

CC = gcc
CFLAGS = -Wall -Wextra -Werror -std=c99
CPATHS = \ # iquotes

SOURCES = \

HEADERS = \

OBJECTS = \

DEPENDENCIES = \

BUILD_DIR = build
DEBUG_DIR = build/debug
RELEASES_DIR = build/releases
LATEST_DIR = build/releases/latest

-include $(DEPENDENCIES)

all: build

build: $(OBJECTS)
	mkdir -p $(RELEASES_DIR)/latest
	ar rcs $(RELEASES_DIR)/latest/bin/latest $(OBJECTS)

debug: CFLAGS += -DDEBUG -g
debug: $(OBJECTS)
	ar rcs $(DEBUG_DIR)/bin/$(NAME) $(OBJECTS)

release: CFLAGS += -03
release: $(OBJECTS)
	mkdir -p $(RELEASES_DIR)/$(RELEASE_NAME)
	ar rcs $(RELEASES_DIR)/$(RELEASE_NAME)/bin/$(RELEASE_NAME)-v${RELEASE_VERSION} $(OBJECTS)

$(NAME): build

clean:
	@$(RM) $(OBJECTS)

fclean: clean
	@$(RM) $(NAME)

re: fclean all

.PHONY: all build debug release $(NAME) clean fclean re

# Rules to compile the source code into object files
objects/allocate.o: source/base/processes/allocate/allocate.c
	$(CC) $(CFLAGS) $(INCLUDES) -o objects/allocate.o 