# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: bhildebr <bhildebr@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/02/24 21:26:55 by bhildebr          #+#    #+#              #
#    Updated: 2024/02/24 21:26:55 by bhildebr         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# This Makefile was automatically generated by Trillian.
# See the source code to learn more.

NAME = libframework.a

DEBUG = ./build/debug/bin/libframework.a
DEFAULT = ./build/default/bin/libframework.a

CC = gcc
CFLAGS = -Wall -Wextra -Werror -std=c99 -g
CPATHS = \
	-include framework.h \
	-include functions.h \
	-include any.h \
	-include cdouble.h \
	-include cint.h \
	-include collection.h \
	-include cstring.h \
	-include memtree.h \
	-include string.h \
	-include table.h \
	-include type.h \
	-iquote ./source \
	-iquote ./source/functions \
	-iquote ./source/types \
	-iquote ./source/types/any \
	-iquote ./source/types/cdouble \
	-iquote ./source/types/cint \
	-iquote ./source/types/collection \
	-iquote ./source/types/cstring \
	-iquote ./source/types/framework \
	-iquote ./source/types/memtree \
	-iquote ./source/types/string \
	-iquote ./source/types/table \
	-iquote ./source/types/type

SOURCES = \
	./source/functions/allocate.c \
	./source/functions/assert.c \
	./source/functions/copy.c \
	./source/functions/create.c \
	./source/functions/deallocate.c \
	./source/functions/debug.c \
	./source/functions/delete.c \
	./source/functions/destroy.c \
	./source/functions/error.c \
	./source/functions/getg.c \
	./source/functions/init.c \
	./source/functions/new.c \
	./source/functions/print.c \
	./source/functions/push.c \
	./source/functions/range.c \
	./source/functions/repeat.c \
	./source/functions/setg.c \
	./source/functions/warning.c \
	./source/types/any/any.c \
	./source/types/any/any_as_cint.c \
	./source/types/any/any_copy.c \
	./source/types/any/any_create.c \
	./source/types/any/any_destroy.c \
	./source/types/cdouble/cdouble.c \
	./source/types/cdouble/cdouble_to_any.c \
	./source/types/cint/cint.c \
	./source/types/cint/cint_abs.c \
	./source/types/cint/cint_to_any.c \
	./source/types/collection/collection.c \
	./source/types/collection/collection_copy.c \
	./source/types/collection/collection_create.c \
	./source/types/collection/collection_destroy.c \
	./source/types/collection/collection_expand.c \
	./source/types/collection/collection_get.c \
	./source/types/collection/collection_get_length.c \
	./source/types/collection/collection_pop.c \
	./source/types/collection/collection_push.c \
	./source/types/collection/collection_reverse.c \
	./source/types/collection/collection_set.c \
	./source/types/collection/collection_shift.c \
	./source/types/collection/collection_to_any.c \
	./source/types/collection/collection_unshift.c \
	./source/types/cstring/cstring.c \
	./source/types/cstring/cstring_to_any.c \
	./source/types/framework/framework_get.c \
	./source/types/framework/framework_get_gtable.c \
	./source/types/framework/framework_get_memtree.c \
	./source/types/memtree/memtree_create.c \
	./source/types/memtree/memtree_delete.c \
	./source/types/memtree/memtree_destroy.c \
	./source/types/memtree/memtree_get.c \
	./source/types/memtree/memtree_get_height.c \
	./source/types/memtree/memtree_insert.c \
	./source/types/memtree/memtree_print.c \
	./source/types/memtree/memtree_rebalance.c \
	./source/types/memtree/memtree_search.c \
	./source/types/memtree/memtree_update_height.c \
	./source/types/string/string.c \
	./source/types/string/string_copy.c \
	./source/types/string/string_create.c \
	./source/types/string/string_destroy.c \
	./source/types/string/string_get.c \
	./source/types/string/string_init.c \
	./source/types/string/string_is_cint.c \
	./source/types/string/string_to_cint.c \
	./source/types/table/table.c \
	./source/types/table/table_copy.c \
	./source/types/table/table_create.c \
	./source/types/table/table_destroy.c \
	./source/types/table/table_expand.c \
	./source/types/table/table_get.c \
	./source/types/table/table_hash.c \
	./source/types/table/table_set.c

OBJECTS = \
	allocate.o \
	assert.o \
	copy.o \
	create.o \
	deallocate.o \
	debug.o \
	delete.o \
	destroy.o \
	error.o \
	getg.o \
	init.o \
	new.o \
	print.o \
	push.o \
	range.o \
	repeat.o \
	setg.o \
	warning.o \
	any.o \
	any_as_cint.o \
	any_copy.o \
	any_create.o \
	any_destroy.o \
	cdouble.o \
	cdouble_to_any.o \
	cint.o \
	cint_abs.o \
	cint_to_any.o \
	collection.o \
	collection_copy.o \
	collection_create.o \
	collection_destroy.o \
	collection_expand.o \
	collection_get.o \
	collection_get_length.o \
	collection_pop.o \
	collection_push.o \
	collection_reverse.o \
	collection_set.o \
	collection_shift.o \
	collection_to_any.o \
	collection_unshift.o \
	cstring.o \
	cstring_to_any.o \
	framework_get.o \
	framework_get_gtable.o \
	framework_get_memtree.o \
	memtree_create.o \
	memtree_delete.o \
	memtree_destroy.o \
	memtree_get.o \
	memtree_get_height.o \
	memtree_insert.o \
	memtree_print.o \
	memtree_rebalance.o \
	memtree_search.o \
	memtree_update_height.o \
	string.o \
	string_copy.o \
	string_create.o \
	string_destroy.o \
	string_get.o \
	string_init.o \
	string_is_cint.o \
	string_to_cint.o \
	table.o \
	table_copy.o \
	table_create.o \
	table_destroy.o \
	table_expand.o \
	table_get.o \
	table_hash.o \
	table_set.o

DEPENDENCIES = \
	allocate.d \
	assert.d \
	copy.d \
	create.d \
	deallocate.d \
	debug.d \
	delete.d \
	destroy.d \
	error.d \
	getg.d \
	init.d \
	new.d \
	print.d \
	push.d \
	range.d \
	repeat.d \
	setg.d \
	warning.d \
	any.d \
	any_as_cint.d \
	any_copy.d \
	any_create.d \
	any_destroy.d \
	cdouble.d \
	cdouble_to_any.d \
	cint.d \
	cint_abs.d \
	cint_to_any.d \
	collection.d \
	collection_copy.d \
	collection_create.d \
	collection_destroy.d \
	collection_expand.d \
	collection_get.d \
	collection_get_length.d \
	collection_pop.d \
	collection_push.d \
	collection_reverse.d \
	collection_set.d \
	collection_shift.d \
	collection_to_any.d \
	collection_unshift.d \
	cstring.d \
	cstring_to_any.d \
	framework_get.d \
	framework_get_gtable.d \
	framework_get_memtree.d \
	memtree_create.d \
	memtree_delete.d \
	memtree_destroy.d \
	memtree_get.d \
	memtree_get_height.d \
	memtree_insert.d \
	memtree_print.d \
	memtree_rebalance.d \
	memtree_search.d \
	memtree_update_height.d \
	string.d \
	string_copy.d \
	string_create.d \
	string_destroy.d \
	string_get.d \
	string_init.d \
	string_is_cint.d \
	string_to_cint.d \
	table.d \
	table_copy.d \
	table_create.d \
	table_destroy.d \
	table_expand.d \
	table_get.d \
	table_hash.d \
	table_set.d

TESTS = \
	build/tests/bin/cint \
	build/tests/bin/collection

TESTS_OBJECTS = \
	build/tests/objects/cint.o \
	build/tests/objects/collection.o

TESTS_DEPENDENCIES = \
	build/tests/dependencies/cint.d \
	build/tests/dependencies/collection.d

DEBUG_DIR = ./build/debug
DEFAULT_DIR = ./build/default
TESTS_DIR = ./build/tests

DEBUG_OBJECTS = $(addprefix $(DEBUG_DIR)/objects/, $(OBJECTS))
DEBUG_DEPENDENCIES = $(addprefix $(DEBUG_DIR)/dependencies/, $(DEPENDENCIES))

DEFAULT_OBJECTS = $(addprefix $(DEFAULT_DIR)/objects/, $(OBJECTS))
DEFAULT_DEPENDENCIES = $(addprefix $(DEFAULT_DIR)/dependencies/, $(DEPENDENCIES))

all: build

$(NAME): build

debug: $(DEBUG)
$(DEBUG): CFLAGS += -DDEBUG
$(DEBUG): $(DEBUG_OBJECTS) | $(DEBUG_DIR)
	@ar rcs $(DEBUG_DIR)/bin/$(NAME) $?

build: $(DEFAULT)
$(DEFAULT): $(DEFAULT_OBJECTS) | $(DEFAULT_DIR)
	@ar rcs $(DEFAULT_DIR)/bin/$(NAME) $?

tests: build $(TESTS)
$(TESTS): $(TESTS_OBJECTS) | $(TESTS_DIR)

clean:
	@$(RM) $(DEBUG_OBJECTS)
	@$(RM) $(DEBUG_DEPENDENCIES)
	@$(RM) $(DEFAULT_OBJECTS)
	@$(RM) $(DEFAULT_DEPENDENCIES)
	@$(RM) $(TESTS_OBJECTS)
	@$(RM) $(TESTS_DEPENDENCIES)

fclean: clean
	@$(RM) $(DEBUG_DIR)/bin/$(NAME)
	@$(RM) $(DEFAULT_DIR)/bin/$(NAME)
	@$(RM) $(TESTS)

re: fclean all

.PHONY: all build debug release $(NAME) clean fclean re

-include $(DEBUG_DEPENDENCIES)
-include $(DEFAULT_DEPENDENCIES)
-include $(TESTS_DEPENDENCIES)

$(DEFAULT_DIR)/objects/allocate.o: ./source/functions/allocate.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/allocate.d -c ./source/functions/allocate.c -o $(DEFAULT_DIR)/objects/allocate.o

$(DEFAULT_DIR)/objects/assert.o: ./source/functions/assert.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/assert.d -c ./source/functions/assert.c -o $(DEFAULT_DIR)/objects/assert.o

$(DEFAULT_DIR)/objects/copy.o: ./source/functions/copy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/copy.d -c ./source/functions/copy.c -o $(DEFAULT_DIR)/objects/copy.o

$(DEFAULT_DIR)/objects/create.o: ./source/functions/create.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/create.d -c ./source/functions/create.c -o $(DEFAULT_DIR)/objects/create.o

$(DEFAULT_DIR)/objects/deallocate.o: ./source/functions/deallocate.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/deallocate.d -c ./source/functions/deallocate.c -o $(DEFAULT_DIR)/objects/deallocate.o

$(DEFAULT_DIR)/objects/debug.o: ./source/functions/debug.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/debug.d -c ./source/functions/debug.c -o $(DEFAULT_DIR)/objects/debug.o

$(DEFAULT_DIR)/objects/delete.o: ./source/functions/delete.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/delete.d -c ./source/functions/delete.c -o $(DEFAULT_DIR)/objects/delete.o

$(DEFAULT_DIR)/objects/destroy.o: ./source/functions/destroy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/destroy.d -c ./source/functions/destroy.c -o $(DEFAULT_DIR)/objects/destroy.o

$(DEFAULT_DIR)/objects/error.o: ./source/functions/error.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/error.d -c ./source/functions/error.c -o $(DEFAULT_DIR)/objects/error.o

$(DEFAULT_DIR)/objects/getg.o: ./source/functions/getg.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/getg.d -c ./source/functions/getg.c -o $(DEFAULT_DIR)/objects/getg.o

$(DEFAULT_DIR)/objects/init.o: ./source/functions/init.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/init.d -c ./source/functions/init.c -o $(DEFAULT_DIR)/objects/init.o

$(DEFAULT_DIR)/objects/new.o: ./source/functions/new.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/new.d -c ./source/functions/new.c -o $(DEFAULT_DIR)/objects/new.o

$(DEFAULT_DIR)/objects/print.o: ./source/functions/print.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/print.d -c ./source/functions/print.c -o $(DEFAULT_DIR)/objects/print.o

$(DEFAULT_DIR)/objects/push.o: ./source/functions/push.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/push.d -c ./source/functions/push.c -o $(DEFAULT_DIR)/objects/push.o

$(DEFAULT_DIR)/objects/range.o: ./source/functions/range.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/range.d -c ./source/functions/range.c -o $(DEFAULT_DIR)/objects/range.o

$(DEFAULT_DIR)/objects/repeat.o: ./source/functions/repeat.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/repeat.d -c ./source/functions/repeat.c -o $(DEFAULT_DIR)/objects/repeat.o

$(DEFAULT_DIR)/objects/setg.o: ./source/functions/setg.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/setg.d -c ./source/functions/setg.c -o $(DEFAULT_DIR)/objects/setg.o

$(DEFAULT_DIR)/objects/warning.o: ./source/functions/warning.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/warning.d -c ./source/functions/warning.c -o $(DEFAULT_DIR)/objects/warning.o

$(DEFAULT_DIR)/objects/any.o: ./source/types/any/any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any.d -c ./source/types/any/any.c -o $(DEFAULT_DIR)/objects/any.o

$(DEFAULT_DIR)/objects/any_as_cint.o: ./source/types/any/any_as_cint.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any_as_cint.d -c ./source/types/any/any_as_cint.c -o $(DEFAULT_DIR)/objects/any_as_cint.o

$(DEFAULT_DIR)/objects/any_copy.o: ./source/types/any/any_copy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any_copy.d -c ./source/types/any/any_copy.c -o $(DEFAULT_DIR)/objects/any_copy.o

$(DEFAULT_DIR)/objects/any_create.o: ./source/types/any/any_create.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any_create.d -c ./source/types/any/any_create.c -o $(DEFAULT_DIR)/objects/any_create.o

$(DEFAULT_DIR)/objects/any_destroy.o: ./source/types/any/any_destroy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any_destroy.d -c ./source/types/any/any_destroy.c -o $(DEFAULT_DIR)/objects/any_destroy.o

$(DEFAULT_DIR)/objects/cdouble.o: ./source/types/cdouble/cdouble.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/cdouble.d -c ./source/types/cdouble/cdouble.c -o $(DEFAULT_DIR)/objects/cdouble.o

$(DEFAULT_DIR)/objects/cdouble_to_any.o: ./source/types/cdouble/cdouble_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/cdouble_to_any.d -c ./source/types/cdouble/cdouble_to_any.c -o $(DEFAULT_DIR)/objects/cdouble_to_any.o

$(DEFAULT_DIR)/objects/cint.o: ./source/types/cint/cint.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/cint.d -c ./source/types/cint/cint.c -o $(DEFAULT_DIR)/objects/cint.o

$(DEFAULT_DIR)/objects/cint_abs.o: ./source/types/cint/cint_abs.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/cint_abs.d -c ./source/types/cint/cint_abs.c -o $(DEFAULT_DIR)/objects/cint_abs.o

$(DEFAULT_DIR)/objects/cint_to_any.o: ./source/types/cint/cint_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/cint_to_any.d -c ./source/types/cint/cint_to_any.c -o $(DEFAULT_DIR)/objects/cint_to_any.o

$(DEFAULT_DIR)/objects/collection.o: ./source/types/collection/collection.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/collection.d -c ./source/types/collection/collection.c -o $(DEFAULT_DIR)/objects/collection.o

$(DEFAULT_DIR)/objects/collection_copy.o: ./source/types/collection/collection_copy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/collection_copy.d -c ./source/types/collection/collection_copy.c -o $(DEFAULT_DIR)/objects/collection_copy.o

$(DEFAULT_DIR)/objects/collection_create.o: ./source/types/collection/collection_create.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/collection_create.d -c ./source/types/collection/collection_create.c -o $(DEFAULT_DIR)/objects/collection_create.o

$(DEFAULT_DIR)/objects/collection_destroy.o: ./source/types/collection/collection_destroy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/collection_destroy.d -c ./source/types/collection/collection_destroy.c -o $(DEFAULT_DIR)/objects/collection_destroy.o

$(DEFAULT_DIR)/objects/collection_expand.o: ./source/types/collection/collection_expand.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/collection_expand.d -c ./source/types/collection/collection_expand.c -o $(DEFAULT_DIR)/objects/collection_expand.o

$(DEFAULT_DIR)/objects/collection_get.o: ./source/types/collection/collection_get.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/collection_get.d -c ./source/types/collection/collection_get.c -o $(DEFAULT_DIR)/objects/collection_get.o

$(DEFAULT_DIR)/objects/collection_get_length.o: ./source/types/collection/collection_get_length.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/collection_get_length.d -c ./source/types/collection/collection_get_length.c -o $(DEFAULT_DIR)/objects/collection_get_length.o

$(DEFAULT_DIR)/objects/collection_pop.o: ./source/types/collection/collection_pop.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/collection_pop.d -c ./source/types/collection/collection_pop.c -o $(DEFAULT_DIR)/objects/collection_pop.o

$(DEFAULT_DIR)/objects/collection_push.o: ./source/types/collection/collection_push.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/collection_push.d -c ./source/types/collection/collection_push.c -o $(DEFAULT_DIR)/objects/collection_push.o

$(DEFAULT_DIR)/objects/collection_reverse.o: ./source/types/collection/collection_reverse.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/collection_reverse.d -c ./source/types/collection/collection_reverse.c -o $(DEFAULT_DIR)/objects/collection_reverse.o

$(DEFAULT_DIR)/objects/collection_set.o: ./source/types/collection/collection_set.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/collection_set.d -c ./source/types/collection/collection_set.c -o $(DEFAULT_DIR)/objects/collection_set.o

$(DEFAULT_DIR)/objects/collection_shift.o: ./source/types/collection/collection_shift.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/collection_shift.d -c ./source/types/collection/collection_shift.c -o $(DEFAULT_DIR)/objects/collection_shift.o

$(DEFAULT_DIR)/objects/collection_to_any.o: ./source/types/collection/collection_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/collection_to_any.d -c ./source/types/collection/collection_to_any.c -o $(DEFAULT_DIR)/objects/collection_to_any.o

$(DEFAULT_DIR)/objects/collection_unshift.o: ./source/types/collection/collection_unshift.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/collection_unshift.d -c ./source/types/collection/collection_unshift.c -o $(DEFAULT_DIR)/objects/collection_unshift.o

$(DEFAULT_DIR)/objects/cstring.o: ./source/types/cstring/cstring.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/cstring.d -c ./source/types/cstring/cstring.c -o $(DEFAULT_DIR)/objects/cstring.o

$(DEFAULT_DIR)/objects/cstring_to_any.o: ./source/types/cstring/cstring_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/cstring_to_any.d -c ./source/types/cstring/cstring_to_any.c -o $(DEFAULT_DIR)/objects/cstring_to_any.o

$(DEFAULT_DIR)/objects/framework_get.o: ./source/types/framework/framework_get.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/framework_get.d -c ./source/types/framework/framework_get.c -o $(DEFAULT_DIR)/objects/framework_get.o

$(DEFAULT_DIR)/objects/framework_get_gtable.o: ./source/types/framework/framework_get_gtable.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/framework_get_gtable.d -c ./source/types/framework/framework_get_gtable.c -o $(DEFAULT_DIR)/objects/framework_get_gtable.o

$(DEFAULT_DIR)/objects/framework_get_memtree.o: ./source/types/framework/framework_get_memtree.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/framework_get_memtree.d -c ./source/types/framework/framework_get_memtree.c -o $(DEFAULT_DIR)/objects/framework_get_memtree.o

$(DEFAULT_DIR)/objects/memtree_create.o: ./source/types/memtree/memtree_create.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/memtree_create.d -c ./source/types/memtree/memtree_create.c -o $(DEFAULT_DIR)/objects/memtree_create.o

$(DEFAULT_DIR)/objects/memtree_delete.o: ./source/types/memtree/memtree_delete.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/memtree_delete.d -c ./source/types/memtree/memtree_delete.c -o $(DEFAULT_DIR)/objects/memtree_delete.o

$(DEFAULT_DIR)/objects/memtree_destroy.o: ./source/types/memtree/memtree_destroy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/memtree_destroy.d -c ./source/types/memtree/memtree_destroy.c -o $(DEFAULT_DIR)/objects/memtree_destroy.o

$(DEFAULT_DIR)/objects/memtree_get.o: ./source/types/memtree/memtree_get.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/memtree_get.d -c ./source/types/memtree/memtree_get.c -o $(DEFAULT_DIR)/objects/memtree_get.o

$(DEFAULT_DIR)/objects/memtree_get_height.o: ./source/types/memtree/memtree_get_height.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/memtree_get_height.d -c ./source/types/memtree/memtree_get_height.c -o $(DEFAULT_DIR)/objects/memtree_get_height.o

$(DEFAULT_DIR)/objects/memtree_insert.o: ./source/types/memtree/memtree_insert.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/memtree_insert.d -c ./source/types/memtree/memtree_insert.c -o $(DEFAULT_DIR)/objects/memtree_insert.o

$(DEFAULT_DIR)/objects/memtree_print.o: ./source/types/memtree/memtree_print.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/memtree_print.d -c ./source/types/memtree/memtree_print.c -o $(DEFAULT_DIR)/objects/memtree_print.o

$(DEFAULT_DIR)/objects/memtree_rebalance.o: ./source/types/memtree/memtree_rebalance.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/memtree_rebalance.d -c ./source/types/memtree/memtree_rebalance.c -o $(DEFAULT_DIR)/objects/memtree_rebalance.o

$(DEFAULT_DIR)/objects/memtree_search.o: ./source/types/memtree/memtree_search.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/memtree_search.d -c ./source/types/memtree/memtree_search.c -o $(DEFAULT_DIR)/objects/memtree_search.o

$(DEFAULT_DIR)/objects/memtree_update_height.o: ./source/types/memtree/memtree_update_height.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/memtree_update_height.d -c ./source/types/memtree/memtree_update_height.c -o $(DEFAULT_DIR)/objects/memtree_update_height.o

$(DEFAULT_DIR)/objects/string.o: ./source/types/string/string.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/string.d -c ./source/types/string/string.c -o $(DEFAULT_DIR)/objects/string.o

$(DEFAULT_DIR)/objects/string_copy.o: ./source/types/string/string_copy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/string_copy.d -c ./source/types/string/string_copy.c -o $(DEFAULT_DIR)/objects/string_copy.o

$(DEFAULT_DIR)/objects/string_create.o: ./source/types/string/string_create.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/string_create.d -c ./source/types/string/string_create.c -o $(DEFAULT_DIR)/objects/string_create.o

$(DEFAULT_DIR)/objects/string_destroy.o: ./source/types/string/string_destroy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/string_destroy.d -c ./source/types/string/string_destroy.c -o $(DEFAULT_DIR)/objects/string_destroy.o

$(DEFAULT_DIR)/objects/string_get.o: ./source/types/string/string_get.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/string_get.d -c ./source/types/string/string_get.c -o $(DEFAULT_DIR)/objects/string_get.o

$(DEFAULT_DIR)/objects/string_init.o: ./source/types/string/string_init.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/string_init.d -c ./source/types/string/string_init.c -o $(DEFAULT_DIR)/objects/string_init.o

$(DEFAULT_DIR)/objects/string_is_cint.o: ./source/types/string/string_is_cint.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/string_is_cint.d -c ./source/types/string/string_is_cint.c -o $(DEFAULT_DIR)/objects/string_is_cint.o

$(DEFAULT_DIR)/objects/string_to_cint.o: ./source/types/string/string_to_cint.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/string_to_cint.d -c ./source/types/string/string_to_cint.c -o $(DEFAULT_DIR)/objects/string_to_cint.o

$(DEFAULT_DIR)/objects/table.o: ./source/types/table/table.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/table.d -c ./source/types/table/table.c -o $(DEFAULT_DIR)/objects/table.o

$(DEFAULT_DIR)/objects/table_copy.o: ./source/types/table/table_copy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/table_copy.d -c ./source/types/table/table_copy.c -o $(DEFAULT_DIR)/objects/table_copy.o

$(DEFAULT_DIR)/objects/table_create.o: ./source/types/table/table_create.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/table_create.d -c ./source/types/table/table_create.c -o $(DEFAULT_DIR)/objects/table_create.o

$(DEFAULT_DIR)/objects/table_destroy.o: ./source/types/table/table_destroy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/table_destroy.d -c ./source/types/table/table_destroy.c -o $(DEFAULT_DIR)/objects/table_destroy.o

$(DEFAULT_DIR)/objects/table_expand.o: ./source/types/table/table_expand.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/table_expand.d -c ./source/types/table/table_expand.c -o $(DEFAULT_DIR)/objects/table_expand.o

$(DEFAULT_DIR)/objects/table_get.o: ./source/types/table/table_get.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/table_get.d -c ./source/types/table/table_get.c -o $(DEFAULT_DIR)/objects/table_get.o

$(DEFAULT_DIR)/objects/table_hash.o: ./source/types/table/table_hash.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/table_hash.d -c ./source/types/table/table_hash.c -o $(DEFAULT_DIR)/objects/table_hash.o

$(DEFAULT_DIR)/objects/table_set.o: ./source/types/table/table_set.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/table_set.d -c ./source/types/table/table_set.c -o $(DEFAULT_DIR)/objects/table_set.o


$(DEBUG_DIR)/objects/allocate.o: ./source/functions/allocate.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/allocate.d -c ./source/functions/allocate.c -o $(DEBUG_DIR)/objects/allocate.o

$(DEBUG_DIR)/objects/assert.o: ./source/functions/assert.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/assert.d -c ./source/functions/assert.c -o $(DEBUG_DIR)/objects/assert.o

$(DEBUG_DIR)/objects/copy.o: ./source/functions/copy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/copy.d -c ./source/functions/copy.c -o $(DEBUG_DIR)/objects/copy.o

$(DEBUG_DIR)/objects/create.o: ./source/functions/create.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/create.d -c ./source/functions/create.c -o $(DEBUG_DIR)/objects/create.o

$(DEBUG_DIR)/objects/deallocate.o: ./source/functions/deallocate.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/deallocate.d -c ./source/functions/deallocate.c -o $(DEBUG_DIR)/objects/deallocate.o

$(DEBUG_DIR)/objects/debug.o: ./source/functions/debug.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/debug.d -c ./source/functions/debug.c -o $(DEBUG_DIR)/objects/debug.o

$(DEBUG_DIR)/objects/delete.o: ./source/functions/delete.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/delete.d -c ./source/functions/delete.c -o $(DEBUG_DIR)/objects/delete.o

$(DEBUG_DIR)/objects/destroy.o: ./source/functions/destroy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/destroy.d -c ./source/functions/destroy.c -o $(DEBUG_DIR)/objects/destroy.o

$(DEBUG_DIR)/objects/error.o: ./source/functions/error.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/error.d -c ./source/functions/error.c -o $(DEBUG_DIR)/objects/error.o

$(DEBUG_DIR)/objects/getg.o: ./source/functions/getg.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/getg.d -c ./source/functions/getg.c -o $(DEBUG_DIR)/objects/getg.o

$(DEBUG_DIR)/objects/init.o: ./source/functions/init.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/init.d -c ./source/functions/init.c -o $(DEBUG_DIR)/objects/init.o

$(DEBUG_DIR)/objects/new.o: ./source/functions/new.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/new.d -c ./source/functions/new.c -o $(DEBUG_DIR)/objects/new.o

$(DEBUG_DIR)/objects/print.o: ./source/functions/print.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/print.d -c ./source/functions/print.c -o $(DEBUG_DIR)/objects/print.o

$(DEBUG_DIR)/objects/push.o: ./source/functions/push.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/push.d -c ./source/functions/push.c -o $(DEBUG_DIR)/objects/push.o

$(DEBUG_DIR)/objects/range.o: ./source/functions/range.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/range.d -c ./source/functions/range.c -o $(DEBUG_DIR)/objects/range.o

$(DEBUG_DIR)/objects/repeat.o: ./source/functions/repeat.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/repeat.d -c ./source/functions/repeat.c -o $(DEBUG_DIR)/objects/repeat.o

$(DEBUG_DIR)/objects/setg.o: ./source/functions/setg.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/setg.d -c ./source/functions/setg.c -o $(DEBUG_DIR)/objects/setg.o

$(DEBUG_DIR)/objects/warning.o: ./source/functions/warning.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/warning.d -c ./source/functions/warning.c -o $(DEBUG_DIR)/objects/warning.o

$(DEBUG_DIR)/objects/any.o: ./source/types/any/any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any.d -c ./source/types/any/any.c -o $(DEBUG_DIR)/objects/any.o

$(DEBUG_DIR)/objects/any_as_cint.o: ./source/types/any/any_as_cint.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any_as_cint.d -c ./source/types/any/any_as_cint.c -o $(DEBUG_DIR)/objects/any_as_cint.o

$(DEBUG_DIR)/objects/any_copy.o: ./source/types/any/any_copy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any_copy.d -c ./source/types/any/any_copy.c -o $(DEBUG_DIR)/objects/any_copy.o

$(DEBUG_DIR)/objects/any_create.o: ./source/types/any/any_create.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any_create.d -c ./source/types/any/any_create.c -o $(DEBUG_DIR)/objects/any_create.o

$(DEBUG_DIR)/objects/any_destroy.o: ./source/types/any/any_destroy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any_destroy.d -c ./source/types/any/any_destroy.c -o $(DEBUG_DIR)/objects/any_destroy.o

$(DEBUG_DIR)/objects/cdouble.o: ./source/types/cdouble/cdouble.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/cdouble.d -c ./source/types/cdouble/cdouble.c -o $(DEBUG_DIR)/objects/cdouble.o

$(DEBUG_DIR)/objects/cdouble_to_any.o: ./source/types/cdouble/cdouble_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/cdouble_to_any.d -c ./source/types/cdouble/cdouble_to_any.c -o $(DEBUG_DIR)/objects/cdouble_to_any.o

$(DEBUG_DIR)/objects/cint.o: ./source/types/cint/cint.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/cint.d -c ./source/types/cint/cint.c -o $(DEBUG_DIR)/objects/cint.o

$(DEBUG_DIR)/objects/cint_abs.o: ./source/types/cint/cint_abs.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/cint_abs.d -c ./source/types/cint/cint_abs.c -o $(DEBUG_DIR)/objects/cint_abs.o

$(DEBUG_DIR)/objects/cint_to_any.o: ./source/types/cint/cint_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/cint_to_any.d -c ./source/types/cint/cint_to_any.c -o $(DEBUG_DIR)/objects/cint_to_any.o

$(DEBUG_DIR)/objects/collection.o: ./source/types/collection/collection.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/collection.d -c ./source/types/collection/collection.c -o $(DEBUG_DIR)/objects/collection.o

$(DEBUG_DIR)/objects/collection_copy.o: ./source/types/collection/collection_copy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/collection_copy.d -c ./source/types/collection/collection_copy.c -o $(DEBUG_DIR)/objects/collection_copy.o

$(DEBUG_DIR)/objects/collection_create.o: ./source/types/collection/collection_create.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/collection_create.d -c ./source/types/collection/collection_create.c -o $(DEBUG_DIR)/objects/collection_create.o

$(DEBUG_DIR)/objects/collection_destroy.o: ./source/types/collection/collection_destroy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/collection_destroy.d -c ./source/types/collection/collection_destroy.c -o $(DEBUG_DIR)/objects/collection_destroy.o

$(DEBUG_DIR)/objects/collection_expand.o: ./source/types/collection/collection_expand.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/collection_expand.d -c ./source/types/collection/collection_expand.c -o $(DEBUG_DIR)/objects/collection_expand.o

$(DEBUG_DIR)/objects/collection_get.o: ./source/types/collection/collection_get.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/collection_get.d -c ./source/types/collection/collection_get.c -o $(DEBUG_DIR)/objects/collection_get.o

$(DEBUG_DIR)/objects/collection_get_length.o: ./source/types/collection/collection_get_length.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/collection_get_length.d -c ./source/types/collection/collection_get_length.c -o $(DEBUG_DIR)/objects/collection_get_length.o

$(DEBUG_DIR)/objects/collection_pop.o: ./source/types/collection/collection_pop.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/collection_pop.d -c ./source/types/collection/collection_pop.c -o $(DEBUG_DIR)/objects/collection_pop.o

$(DEBUG_DIR)/objects/collection_push.o: ./source/types/collection/collection_push.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/collection_push.d -c ./source/types/collection/collection_push.c -o $(DEBUG_DIR)/objects/collection_push.o

$(DEBUG_DIR)/objects/collection_reverse.o: ./source/types/collection/collection_reverse.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/collection_reverse.d -c ./source/types/collection/collection_reverse.c -o $(DEBUG_DIR)/objects/collection_reverse.o

$(DEBUG_DIR)/objects/collection_set.o: ./source/types/collection/collection_set.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/collection_set.d -c ./source/types/collection/collection_set.c -o $(DEBUG_DIR)/objects/collection_set.o

$(DEBUG_DIR)/objects/collection_shift.o: ./source/types/collection/collection_shift.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/collection_shift.d -c ./source/types/collection/collection_shift.c -o $(DEBUG_DIR)/objects/collection_shift.o

$(DEBUG_DIR)/objects/collection_to_any.o: ./source/types/collection/collection_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/collection_to_any.d -c ./source/types/collection/collection_to_any.c -o $(DEBUG_DIR)/objects/collection_to_any.o

$(DEBUG_DIR)/objects/collection_unshift.o: ./source/types/collection/collection_unshift.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/collection_unshift.d -c ./source/types/collection/collection_unshift.c -o $(DEBUG_DIR)/objects/collection_unshift.o

$(DEBUG_DIR)/objects/cstring.o: ./source/types/cstring/cstring.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/cstring.d -c ./source/types/cstring/cstring.c -o $(DEBUG_DIR)/objects/cstring.o

$(DEBUG_DIR)/objects/cstring_to_any.o: ./source/types/cstring/cstring_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/cstring_to_any.d -c ./source/types/cstring/cstring_to_any.c -o $(DEBUG_DIR)/objects/cstring_to_any.o

$(DEBUG_DIR)/objects/framework_get.o: ./source/types/framework/framework_get.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/framework_get.d -c ./source/types/framework/framework_get.c -o $(DEBUG_DIR)/objects/framework_get.o

$(DEBUG_DIR)/objects/framework_get_gtable.o: ./source/types/framework/framework_get_gtable.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/framework_get_gtable.d -c ./source/types/framework/framework_get_gtable.c -o $(DEBUG_DIR)/objects/framework_get_gtable.o

$(DEBUG_DIR)/objects/framework_get_memtree.o: ./source/types/framework/framework_get_memtree.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/framework_get_memtree.d -c ./source/types/framework/framework_get_memtree.c -o $(DEBUG_DIR)/objects/framework_get_memtree.o

$(DEBUG_DIR)/objects/memtree_create.o: ./source/types/memtree/memtree_create.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/memtree_create.d -c ./source/types/memtree/memtree_create.c -o $(DEBUG_DIR)/objects/memtree_create.o

$(DEBUG_DIR)/objects/memtree_delete.o: ./source/types/memtree/memtree_delete.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/memtree_delete.d -c ./source/types/memtree/memtree_delete.c -o $(DEBUG_DIR)/objects/memtree_delete.o

$(DEBUG_DIR)/objects/memtree_destroy.o: ./source/types/memtree/memtree_destroy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/memtree_destroy.d -c ./source/types/memtree/memtree_destroy.c -o $(DEBUG_DIR)/objects/memtree_destroy.o

$(DEBUG_DIR)/objects/memtree_get.o: ./source/types/memtree/memtree_get.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/memtree_get.d -c ./source/types/memtree/memtree_get.c -o $(DEBUG_DIR)/objects/memtree_get.o

$(DEBUG_DIR)/objects/memtree_get_height.o: ./source/types/memtree/memtree_get_height.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/memtree_get_height.d -c ./source/types/memtree/memtree_get_height.c -o $(DEBUG_DIR)/objects/memtree_get_height.o

$(DEBUG_DIR)/objects/memtree_insert.o: ./source/types/memtree/memtree_insert.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/memtree_insert.d -c ./source/types/memtree/memtree_insert.c -o $(DEBUG_DIR)/objects/memtree_insert.o

$(DEBUG_DIR)/objects/memtree_print.o: ./source/types/memtree/memtree_print.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/memtree_print.d -c ./source/types/memtree/memtree_print.c -o $(DEBUG_DIR)/objects/memtree_print.o

$(DEBUG_DIR)/objects/memtree_rebalance.o: ./source/types/memtree/memtree_rebalance.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/memtree_rebalance.d -c ./source/types/memtree/memtree_rebalance.c -o $(DEBUG_DIR)/objects/memtree_rebalance.o

$(DEBUG_DIR)/objects/memtree_search.o: ./source/types/memtree/memtree_search.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/memtree_search.d -c ./source/types/memtree/memtree_search.c -o $(DEBUG_DIR)/objects/memtree_search.o

$(DEBUG_DIR)/objects/memtree_update_height.o: ./source/types/memtree/memtree_update_height.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/memtree_update_height.d -c ./source/types/memtree/memtree_update_height.c -o $(DEBUG_DIR)/objects/memtree_update_height.o

$(DEBUG_DIR)/objects/string.o: ./source/types/string/string.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/string.d -c ./source/types/string/string.c -o $(DEBUG_DIR)/objects/string.o

$(DEBUG_DIR)/objects/string_copy.o: ./source/types/string/string_copy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/string_copy.d -c ./source/types/string/string_copy.c -o $(DEBUG_DIR)/objects/string_copy.o

$(DEBUG_DIR)/objects/string_create.o: ./source/types/string/string_create.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/string_create.d -c ./source/types/string/string_create.c -o $(DEBUG_DIR)/objects/string_create.o

$(DEBUG_DIR)/objects/string_destroy.o: ./source/types/string/string_destroy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/string_destroy.d -c ./source/types/string/string_destroy.c -o $(DEBUG_DIR)/objects/string_destroy.o

$(DEBUG_DIR)/objects/string_get.o: ./source/types/string/string_get.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/string_get.d -c ./source/types/string/string_get.c -o $(DEBUG_DIR)/objects/string_get.o

$(DEBUG_DIR)/objects/string_init.o: ./source/types/string/string_init.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/string_init.d -c ./source/types/string/string_init.c -o $(DEBUG_DIR)/objects/string_init.o

$(DEBUG_DIR)/objects/string_is_cint.o: ./source/types/string/string_is_cint.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/string_is_cint.d -c ./source/types/string/string_is_cint.c -o $(DEBUG_DIR)/objects/string_is_cint.o

$(DEBUG_DIR)/objects/string_to_cint.o: ./source/types/string/string_to_cint.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/string_to_cint.d -c ./source/types/string/string_to_cint.c -o $(DEBUG_DIR)/objects/string_to_cint.o

$(DEBUG_DIR)/objects/table.o: ./source/types/table/table.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/table.d -c ./source/types/table/table.c -o $(DEBUG_DIR)/objects/table.o

$(DEBUG_DIR)/objects/table_copy.o: ./source/types/table/table_copy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/table_copy.d -c ./source/types/table/table_copy.c -o $(DEBUG_DIR)/objects/table_copy.o

$(DEBUG_DIR)/objects/table_create.o: ./source/types/table/table_create.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/table_create.d -c ./source/types/table/table_create.c -o $(DEBUG_DIR)/objects/table_create.o

$(DEBUG_DIR)/objects/table_destroy.o: ./source/types/table/table_destroy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/table_destroy.d -c ./source/types/table/table_destroy.c -o $(DEBUG_DIR)/objects/table_destroy.o

$(DEBUG_DIR)/objects/table_expand.o: ./source/types/table/table_expand.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/table_expand.d -c ./source/types/table/table_expand.c -o $(DEBUG_DIR)/objects/table_expand.o

$(DEBUG_DIR)/objects/table_get.o: ./source/types/table/table_get.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/table_get.d -c ./source/types/table/table_get.c -o $(DEBUG_DIR)/objects/table_get.o

$(DEBUG_DIR)/objects/table_hash.o: ./source/types/table/table_hash.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/table_hash.d -c ./source/types/table/table_hash.c -o $(DEBUG_DIR)/objects/table_hash.o

$(DEBUG_DIR)/objects/table_set.o: ./source/types/table/table_set.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/table_set.d -c ./source/types/table/table_set.c -o $(DEBUG_DIR)/objects/table_set.o


$(TESTS_DIR)/objects/cint.o: ./tests/types/cint.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(TESTS_DIR)/dependencies/cint.d -c ./tests/types/cint.c -o $(TESTS_DIR)/objects/cint.o
	@$(CC) $(CFLAGS) $(CPATHS) $(TESTS_DIR)/objects/cint.o $(DEFAULT) -o $(TESTS_DIR)/bin/cint

$(TESTS_DIR)/objects/collection.o: ./tests/types/collection.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(TESTS_DIR)/dependencies/collection.d -c ./tests/types/collection.c -o $(TESTS_DIR)/objects/collection.o
	@$(CC) $(CFLAGS) $(CPATHS) $(TESTS_DIR)/objects/collection.o $(DEFAULT) -o $(TESTS_DIR)/bin/collection


