# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: bhildebr <bhildebr@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/03/01 15:26:57 by bhildebr          #+#    #+#              #
#    Updated: 2024/03/01 15:26:57 by bhildebr         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# This Makefile was automatically generated by Trillian.
# See the source code to learn more.

NAME = libframework.a

DEBUG = ./build/debug/bin/libframework.a
DEFAULT = ./build/default/bin/libframework.a

CC = gcc
CFLAGS = -Wall -Wextra -Werror -std=c99 -g
CPATHS = \
	-include framework.h \
	-include functions.h \
	-include any.h \
	-include f64.h \
	-include i32.h \
	-include i64.h \
	-include i8.h \
	-include list.h \
	-include map.h \
	-include memtree.h \
	-include type.h \
	-include u32.h \
	-include u64.h \
	-include u8.h \
	-iquote ./source \
	-iquote ./source/functions \
	-iquote ./source/types \
	-iquote ./source/types/any \
	-iquote ./source/types/f64 \
	-iquote ./source/types/framework \
	-iquote ./source/types/graph \
	-iquote ./source/types/i32 \
	-iquote ./source/types/i64 \
	-iquote ./source/types/i8 \
	-iquote ./source/types/list \
	-iquote ./source/types/map \
	-iquote ./source/types/memtree \
	-iquote ./source/types/type \
	-iquote ./source/types/u32 \
	-iquote ./source/types/u64 \
	-iquote ./source/types/u8

SOURCES = \
	./source/functions/allocate.c \
	./source/functions/assert.c \
	./source/functions/as_any.c \
	./source/functions/compare.c \
	./source/functions/conceal.c \
	./source/functions/copy.c \
	./source/functions/create.c \
	./source/functions/deallocate.c \
	./source/functions/debug.c \
	./source/functions/delete.c \
	./source/functions/destroy.c \
	./source/functions/display.c \
	./source/functions/error.c \
	./source/functions/filter.c \
	./source/functions/find.c \
	./source/functions/foreach.c \
	./source/functions/forkrun.c \
	./source/functions/init.c \
	./source/functions/new.c \
	./source/functions/print.c \
	./source/functions/push.c \
	./source/functions/quit.c \
	./source/functions/range.c \
	./source/functions/reduce.c \
	./source/functions/repeat.c \
	./source/functions/retrieve.c \
	./source/functions/share.c \
	./source/functions/slice.c \
	./source/functions/to_any.c \
	./source/functions/warning.c \
	./source/types/any/any.c \
	./source/types/any/any_as_f64.c \
	./source/types/any/any_as_i32.c \
	./source/types/any/any_as_i64.c \
	./source/types/any/any_as_i8.c \
	./source/types/any/any_as_instance.c \
	./source/types/any/any_as_sequence.c \
	./source/types/any/any_as_u32.c \
	./source/types/any/any_as_u64.c \
	./source/types/any/any_as_u8.c \
	./source/types/any/any_copy.c \
	./source/types/any/any_create.c \
	./source/types/any/any_destroy.c \
	./source/types/any/any_to_f64.c \
	./source/types/any/any_to_i32.c \
	./source/types/any/any_to_i64.c \
	./source/types/any/any_to_i8.c \
	./source/types/any/any_to_instance.c \
	./source/types/any/any_to_sequence.c \
	./source/types/any/any_to_u32.c \
	./source/types/any/any_to_u64.c \
	./source/types/any/any_to_u8.c \
	./source/types/f64/f64.c \
	./source/types/f64/f64_to_any.c \
	./source/types/framework/framework_get.c \
	./source/types/framework/framework_get_map.c \
	./source/types/framework/framework_get_memtree.c \
	./source/types/i32/i32.c \
	./source/types/i32/i32_to_any.c \
	./source/types/i64/i64.c \
	./source/types/i64/i64_is_i32.c \
	./source/types/i64/i64_to_any.c \
	./source/types/i8/i8.c \
	./source/types/i8/i8_is_digit.c \
	./source/types/i8/i8_is_signal.c \
	./source/types/i8/i8_is_space.c \
	./source/types/i8/i8_sequence.c \
	./source/types/i8/i8_sequence_is_i32.c \
	./source/types/i8/i8_sequence_to_any.c \
	./source/types/i8/i8_sequence_to_i32.c \
	./source/types/i8/i8_to_any.c \
	./source/types/list/list.c \
	./source/types/list/list_as_any.c \
	./source/types/list/list_copy.c \
	./source/types/list/list_create.c \
	./source/types/list/list_destroy.c \
	./source/types/list/list_expand.c \
	./source/types/list/list_get.c \
	./source/types/list/list_get_length.c \
	./source/types/list/list_pop.c \
	./source/types/list/list_push.c \
	./source/types/list/list_reverse.c \
	./source/types/list/list_set.c \
	./source/types/list/list_shift.c \
	./source/types/list/list_unshift.c \
	./source/types/map/map.c \
	./source/types/map/map_copy.c \
	./source/types/map/map_create.c \
	./source/types/map/map_destroy.c \
	./source/types/map/map_expand.c \
	./source/types/map/map_get.c \
	./source/types/map/map_hash.c \
	./source/types/map/map_set.c \
	./source/types/memtree/memtree_create.c \
	./source/types/memtree/memtree_delete.c \
	./source/types/memtree/memtree_destroy.c \
	./source/types/memtree/memtree_get.c \
	./source/types/memtree/memtree_get_height.c \
	./source/types/memtree/memtree_insert.c \
	./source/types/memtree/memtree_print.c \
	./source/types/memtree/memtree_rebalance.c \
	./source/types/memtree/memtree_search.c \
	./source/types/memtree/memtree_update_height.c \
	./source/types/u32/u32.c \
	./source/types/u32/u32_to_any.c \
	./source/types/u64/u64.c \
	./source/types/u64/u64_to_any.c \
	./source/types/u8/u8.c \
	./source/types/u8/u8_to_any.c

OBJECTS = \
	allocate.o \
	assert.o \
	as_any.o \
	compare.o \
	conceal.o \
	copy.o \
	create.o \
	deallocate.o \
	debug.o \
	delete.o \
	destroy.o \
	display.o \
	error.o \
	filter.o \
	find.o \
	foreach.o \
	forkrun.o \
	init.o \
	new.o \
	print.o \
	push.o \
	quit.o \
	range.o \
	reduce.o \
	repeat.o \
	retrieve.o \
	share.o \
	slice.o \
	to_any.o \
	warning.o \
	any.o \
	any_as_f64.o \
	any_as_i32.o \
	any_as_i64.o \
	any_as_i8.o \
	any_as_instance.o \
	any_as_sequence.o \
	any_as_u32.o \
	any_as_u64.o \
	any_as_u8.o \
	any_copy.o \
	any_create.o \
	any_destroy.o \
	any_to_f64.o \
	any_to_i32.o \
	any_to_i64.o \
	any_to_i8.o \
	any_to_instance.o \
	any_to_sequence.o \
	any_to_u32.o \
	any_to_u64.o \
	any_to_u8.o \
	f64.o \
	f64_to_any.o \
	framework_get.o \
	framework_get_map.o \
	framework_get_memtree.o \
	i32.o \
	i32_to_any.o \
	i64.o \
	i64_is_i32.o \
	i64_to_any.o \
	i8.o \
	i8_is_digit.o \
	i8_is_signal.o \
	i8_is_space.o \
	i8_sequence.o \
	i8_sequence_is_i32.o \
	i8_sequence_to_any.o \
	i8_sequence_to_i32.o \
	i8_to_any.o \
	list.o \
	list_as_any.o \
	list_copy.o \
	list_create.o \
	list_destroy.o \
	list_expand.o \
	list_get.o \
	list_get_length.o \
	list_pop.o \
	list_push.o \
	list_reverse.o \
	list_set.o \
	list_shift.o \
	list_unshift.o \
	map.o \
	map_copy.o \
	map_create.o \
	map_destroy.o \
	map_expand.o \
	map_get.o \
	map_hash.o \
	map_set.o \
	memtree_create.o \
	memtree_delete.o \
	memtree_destroy.o \
	memtree_get.o \
	memtree_get_height.o \
	memtree_insert.o \
	memtree_print.o \
	memtree_rebalance.o \
	memtree_search.o \
	memtree_update_height.o \
	u32.o \
	u32_to_any.o \
	u64.o \
	u64_to_any.o \
	u8.o \
	u8_to_any.o

DEPENDENCIES = \
	allocate.d \
	assert.d \
	as_any.d \
	compare.d \
	conceal.d \
	copy.d \
	create.d \
	deallocate.d \
	debug.d \
	delete.d \
	destroy.d \
	display.d \
	error.d \
	filter.d \
	find.d \
	foreach.d \
	forkrun.d \
	init.d \
	new.d \
	print.d \
	push.d \
	quit.d \
	range.d \
	reduce.d \
	repeat.d \
	retrieve.d \
	share.d \
	slice.d \
	to_any.d \
	warning.d \
	any.d \
	any_as_f64.d \
	any_as_i32.d \
	any_as_i64.d \
	any_as_i8.d \
	any_as_instance.d \
	any_as_sequence.d \
	any_as_u32.d \
	any_as_u64.d \
	any_as_u8.d \
	any_copy.d \
	any_create.d \
	any_destroy.d \
	any_to_f64.d \
	any_to_i32.d \
	any_to_i64.d \
	any_to_i8.d \
	any_to_instance.d \
	any_to_sequence.d \
	any_to_u32.d \
	any_to_u64.d \
	any_to_u8.d \
	f64.d \
	f64_to_any.d \
	framework_get.d \
	framework_get_map.d \
	framework_get_memtree.d \
	i32.d \
	i32_to_any.d \
	i64.d \
	i64_is_i32.d \
	i64_to_any.d \
	i8.d \
	i8_is_digit.d \
	i8_is_signal.d \
	i8_is_space.d \
	i8_sequence.d \
	i8_sequence_is_i32.d \
	i8_sequence_to_any.d \
	i8_sequence_to_i32.d \
	i8_to_any.d \
	list.d \
	list_as_any.d \
	list_copy.d \
	list_create.d \
	list_destroy.d \
	list_expand.d \
	list_get.d \
	list_get_length.d \
	list_pop.d \
	list_push.d \
	list_reverse.d \
	list_set.d \
	list_shift.d \
	list_unshift.d \
	map.d \
	map_copy.d \
	map_create.d \
	map_destroy.d \
	map_expand.d \
	map_get.d \
	map_hash.d \
	map_set.d \
	memtree_create.d \
	memtree_delete.d \
	memtree_destroy.d \
	memtree_get.d \
	memtree_get_height.d \
	memtree_insert.d \
	memtree_print.d \
	memtree_rebalance.d \
	memtree_search.d \
	memtree_update_height.d \
	u32.d \
	u32_to_any.d \
	u64.d \
	u64_to_any.d \
	u8.d \
	u8_to_any.d

TESTS = \
	build/tests/bin/allocate \
	build/tests/bin/assert \
	build/tests/bin/deallocate \
	build/tests/bin/debug \
	build/tests/bin/delete \
	build/tests/bin/display \
	build/tests/bin/error \
	build/tests/bin/forkrun \
	build/tests/bin/new \
	build/tests/bin/repeat \
	build/tests/bin/warning \
	build/tests/bin/any \
	build/tests/bin/framework \
	build/tests/bin/map \
	build/tests/bin/memtree \
	build/tests/bin/string \
	build/tests/bin/type

TESTS_OBJECTS = \
	build/tests/objects/allocate.o \
	build/tests/objects/assert.o \
	build/tests/objects/deallocate.o \
	build/tests/objects/debug.o \
	build/tests/objects/delete.o \
	build/tests/objects/display.o \
	build/tests/objects/error.o \
	build/tests/objects/forkrun.o \
	build/tests/objects/new.o \
	build/tests/objects/repeat.o \
	build/tests/objects/warning.o \
	build/tests/objects/any.o \
	build/tests/objects/framework.o \
	build/tests/objects/map.o \
	build/tests/objects/memtree.o \
	build/tests/objects/string.o \
	build/tests/objects/type.o

TESTS_DEPENDENCIES = \
	build/tests/dependencies/allocate.d \
	build/tests/dependencies/assert.d \
	build/tests/dependencies/deallocate.d \
	build/tests/dependencies/debug.d \
	build/tests/dependencies/delete.d \
	build/tests/dependencies/display.d \
	build/tests/dependencies/error.d \
	build/tests/dependencies/forkrun.d \
	build/tests/dependencies/new.d \
	build/tests/dependencies/repeat.d \
	build/tests/dependencies/warning.d \
	build/tests/dependencies/any.d \
	build/tests/dependencies/framework.d \
	build/tests/dependencies/map.d \
	build/tests/dependencies/memtree.d \
	build/tests/dependencies/string.d \
	build/tests/dependencies/type.d

DEBUG_DIR = ./build/debug
DEFAULT_DIR = ./build/default
TESTS_DIR = ./build/tests

DEBUG_OBJECTS = $(addprefix $(DEBUG_DIR)/objects/, $(OBJECTS))
DEBUG_DEPENDENCIES = $(addprefix $(DEBUG_DIR)/dependencies/, $(DEPENDENCIES))

DEFAULT_OBJECTS = $(addprefix $(DEFAULT_DIR)/objects/, $(OBJECTS))
DEFAULT_DEPENDENCIES = $(addprefix $(DEFAULT_DIR)/dependencies/, $(DEPENDENCIES))

all: build

$(NAME): build

debug: $(DEBUG)
$(DEBUG): CFLAGS += -DDEBUG
$(DEBUG): $(DEBUG_OBJECTS) | $(DEBUG_DIR)
	@ar rcs $(DEBUG_DIR)/bin/$(NAME) $?

build: $(DEFAULT)
$(DEFAULT): $(DEFAULT_OBJECTS) | $(DEFAULT_DIR)
	@ar rcs $(DEFAULT_DIR)/bin/$(NAME) $?

tests: build $(TESTS)
$(TESTS): $(TESTS_OBJECTS) | $(TESTS_DIR)

$(TESTS_OBJECTS): $(DEFAULT_OBJECTS)

clean:
	@$(RM) $(DEBUG_OBJECTS)
	@$(RM) $(DEBUG_DEPENDENCIES)
	@$(RM) $(DEFAULT_OBJECTS)
	@$(RM) $(DEFAULT_DEPENDENCIES)
	@$(RM) $(TESTS_OBJECTS)
	@$(RM) $(TESTS_DEPENDENCIES)

fclean: clean
	@$(RM) $(DEBUG_DIR)/bin/$(NAME)
	@$(RM) $(DEFAULT_DIR)/bin/$(NAME)
	@$(RM) $(TESTS)

re: fclean all

.PHONY: all build debug release $(NAME) clean fclean re

-include $(DEBUG_DEPENDENCIES)
-include $(DEFAULT_DEPENDENCIES)
-include $(TESTS_DEPENDENCIES)

$(DEFAULT_DIR)/objects/allocate.o: ./source/functions/allocate.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/allocate.d -c ./source/functions/allocate.c -o $(DEFAULT_DIR)/objects/allocate.o

$(DEFAULT_DIR)/objects/assert.o: ./source/functions/assert.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/assert.d -c ./source/functions/assert.c -o $(DEFAULT_DIR)/objects/assert.o

$(DEFAULT_DIR)/objects/as_any.o: ./source/functions/as_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/as_any.d -c ./source/functions/as_any.c -o $(DEFAULT_DIR)/objects/as_any.o

$(DEFAULT_DIR)/objects/compare.o: ./source/functions/compare.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/compare.d -c ./source/functions/compare.c -o $(DEFAULT_DIR)/objects/compare.o

$(DEFAULT_DIR)/objects/conceal.o: ./source/functions/conceal.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/conceal.d -c ./source/functions/conceal.c -o $(DEFAULT_DIR)/objects/conceal.o

$(DEFAULT_DIR)/objects/copy.o: ./source/functions/copy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/copy.d -c ./source/functions/copy.c -o $(DEFAULT_DIR)/objects/copy.o

$(DEFAULT_DIR)/objects/create.o: ./source/functions/create.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/create.d -c ./source/functions/create.c -o $(DEFAULT_DIR)/objects/create.o

$(DEFAULT_DIR)/objects/deallocate.o: ./source/functions/deallocate.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/deallocate.d -c ./source/functions/deallocate.c -o $(DEFAULT_DIR)/objects/deallocate.o

$(DEFAULT_DIR)/objects/debug.o: ./source/functions/debug.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/debug.d -c ./source/functions/debug.c -o $(DEFAULT_DIR)/objects/debug.o

$(DEFAULT_DIR)/objects/delete.o: ./source/functions/delete.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/delete.d -c ./source/functions/delete.c -o $(DEFAULT_DIR)/objects/delete.o

$(DEFAULT_DIR)/objects/destroy.o: ./source/functions/destroy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/destroy.d -c ./source/functions/destroy.c -o $(DEFAULT_DIR)/objects/destroy.o

$(DEFAULT_DIR)/objects/display.o: ./source/functions/display.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/display.d -c ./source/functions/display.c -o $(DEFAULT_DIR)/objects/display.o

$(DEFAULT_DIR)/objects/error.o: ./source/functions/error.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/error.d -c ./source/functions/error.c -o $(DEFAULT_DIR)/objects/error.o

$(DEFAULT_DIR)/objects/filter.o: ./source/functions/filter.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/filter.d -c ./source/functions/filter.c -o $(DEFAULT_DIR)/objects/filter.o

$(DEFAULT_DIR)/objects/find.o: ./source/functions/find.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/find.d -c ./source/functions/find.c -o $(DEFAULT_DIR)/objects/find.o

$(DEFAULT_DIR)/objects/foreach.o: ./source/functions/foreach.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/foreach.d -c ./source/functions/foreach.c -o $(DEFAULT_DIR)/objects/foreach.o

$(DEFAULT_DIR)/objects/forkrun.o: ./source/functions/forkrun.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/forkrun.d -c ./source/functions/forkrun.c -o $(DEFAULT_DIR)/objects/forkrun.o

$(DEFAULT_DIR)/objects/init.o: ./source/functions/init.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/init.d -c ./source/functions/init.c -o $(DEFAULT_DIR)/objects/init.o

$(DEFAULT_DIR)/objects/new.o: ./source/functions/new.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/new.d -c ./source/functions/new.c -o $(DEFAULT_DIR)/objects/new.o

$(DEFAULT_DIR)/objects/print.o: ./source/functions/print.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/print.d -c ./source/functions/print.c -o $(DEFAULT_DIR)/objects/print.o

$(DEFAULT_DIR)/objects/push.o: ./source/functions/push.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/push.d -c ./source/functions/push.c -o $(DEFAULT_DIR)/objects/push.o

$(DEFAULT_DIR)/objects/quit.o: ./source/functions/quit.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/quit.d -c ./source/functions/quit.c -o $(DEFAULT_DIR)/objects/quit.o

$(DEFAULT_DIR)/objects/range.o: ./source/functions/range.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/range.d -c ./source/functions/range.c -o $(DEFAULT_DIR)/objects/range.o

$(DEFAULT_DIR)/objects/reduce.o: ./source/functions/reduce.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/reduce.d -c ./source/functions/reduce.c -o $(DEFAULT_DIR)/objects/reduce.o

$(DEFAULT_DIR)/objects/repeat.o: ./source/functions/repeat.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/repeat.d -c ./source/functions/repeat.c -o $(DEFAULT_DIR)/objects/repeat.o

$(DEFAULT_DIR)/objects/retrieve.o: ./source/functions/retrieve.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/retrieve.d -c ./source/functions/retrieve.c -o $(DEFAULT_DIR)/objects/retrieve.o

$(DEFAULT_DIR)/objects/share.o: ./source/functions/share.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/share.d -c ./source/functions/share.c -o $(DEFAULT_DIR)/objects/share.o

$(DEFAULT_DIR)/objects/slice.o: ./source/functions/slice.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/slice.d -c ./source/functions/slice.c -o $(DEFAULT_DIR)/objects/slice.o

$(DEFAULT_DIR)/objects/to_any.o: ./source/functions/to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/to_any.d -c ./source/functions/to_any.c -o $(DEFAULT_DIR)/objects/to_any.o

$(DEFAULT_DIR)/objects/warning.o: ./source/functions/warning.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/warning.d -c ./source/functions/warning.c -o $(DEFAULT_DIR)/objects/warning.o

$(DEFAULT_DIR)/objects/any.o: ./source/types/any/any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any.d -c ./source/types/any/any.c -o $(DEFAULT_DIR)/objects/any.o

$(DEFAULT_DIR)/objects/any_as_f64.o: ./source/types/any/any_as_f64.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any_as_f64.d -c ./source/types/any/any_as_f64.c -o $(DEFAULT_DIR)/objects/any_as_f64.o

$(DEFAULT_DIR)/objects/any_as_i32.o: ./source/types/any/any_as_i32.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any_as_i32.d -c ./source/types/any/any_as_i32.c -o $(DEFAULT_DIR)/objects/any_as_i32.o

$(DEFAULT_DIR)/objects/any_as_i64.o: ./source/types/any/any_as_i64.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any_as_i64.d -c ./source/types/any/any_as_i64.c -o $(DEFAULT_DIR)/objects/any_as_i64.o

$(DEFAULT_DIR)/objects/any_as_i8.o: ./source/types/any/any_as_i8.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any_as_i8.d -c ./source/types/any/any_as_i8.c -o $(DEFAULT_DIR)/objects/any_as_i8.o

$(DEFAULT_DIR)/objects/any_as_instance.o: ./source/types/any/any_as_instance.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any_as_instance.d -c ./source/types/any/any_as_instance.c -o $(DEFAULT_DIR)/objects/any_as_instance.o

$(DEFAULT_DIR)/objects/any_as_sequence.o: ./source/types/any/any_as_sequence.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any_as_sequence.d -c ./source/types/any/any_as_sequence.c -o $(DEFAULT_DIR)/objects/any_as_sequence.o

$(DEFAULT_DIR)/objects/any_as_u32.o: ./source/types/any/any_as_u32.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any_as_u32.d -c ./source/types/any/any_as_u32.c -o $(DEFAULT_DIR)/objects/any_as_u32.o

$(DEFAULT_DIR)/objects/any_as_u64.o: ./source/types/any/any_as_u64.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any_as_u64.d -c ./source/types/any/any_as_u64.c -o $(DEFAULT_DIR)/objects/any_as_u64.o

$(DEFAULT_DIR)/objects/any_as_u8.o: ./source/types/any/any_as_u8.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any_as_u8.d -c ./source/types/any/any_as_u8.c -o $(DEFAULT_DIR)/objects/any_as_u8.o

$(DEFAULT_DIR)/objects/any_copy.o: ./source/types/any/any_copy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any_copy.d -c ./source/types/any/any_copy.c -o $(DEFAULT_DIR)/objects/any_copy.o

$(DEFAULT_DIR)/objects/any_create.o: ./source/types/any/any_create.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any_create.d -c ./source/types/any/any_create.c -o $(DEFAULT_DIR)/objects/any_create.o

$(DEFAULT_DIR)/objects/any_destroy.o: ./source/types/any/any_destroy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any_destroy.d -c ./source/types/any/any_destroy.c -o $(DEFAULT_DIR)/objects/any_destroy.o

$(DEFAULT_DIR)/objects/any_to_f64.o: ./source/types/any/any_to_f64.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any_to_f64.d -c ./source/types/any/any_to_f64.c -o $(DEFAULT_DIR)/objects/any_to_f64.o

$(DEFAULT_DIR)/objects/any_to_i32.o: ./source/types/any/any_to_i32.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any_to_i32.d -c ./source/types/any/any_to_i32.c -o $(DEFAULT_DIR)/objects/any_to_i32.o

$(DEFAULT_DIR)/objects/any_to_i64.o: ./source/types/any/any_to_i64.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any_to_i64.d -c ./source/types/any/any_to_i64.c -o $(DEFAULT_DIR)/objects/any_to_i64.o

$(DEFAULT_DIR)/objects/any_to_i8.o: ./source/types/any/any_to_i8.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any_to_i8.d -c ./source/types/any/any_to_i8.c -o $(DEFAULT_DIR)/objects/any_to_i8.o

$(DEFAULT_DIR)/objects/any_to_instance.o: ./source/types/any/any_to_instance.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any_to_instance.d -c ./source/types/any/any_to_instance.c -o $(DEFAULT_DIR)/objects/any_to_instance.o

$(DEFAULT_DIR)/objects/any_to_sequence.o: ./source/types/any/any_to_sequence.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any_to_sequence.d -c ./source/types/any/any_to_sequence.c -o $(DEFAULT_DIR)/objects/any_to_sequence.o

$(DEFAULT_DIR)/objects/any_to_u32.o: ./source/types/any/any_to_u32.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any_to_u32.d -c ./source/types/any/any_to_u32.c -o $(DEFAULT_DIR)/objects/any_to_u32.o

$(DEFAULT_DIR)/objects/any_to_u64.o: ./source/types/any/any_to_u64.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any_to_u64.d -c ./source/types/any/any_to_u64.c -o $(DEFAULT_DIR)/objects/any_to_u64.o

$(DEFAULT_DIR)/objects/any_to_u8.o: ./source/types/any/any_to_u8.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any_to_u8.d -c ./source/types/any/any_to_u8.c -o $(DEFAULT_DIR)/objects/any_to_u8.o

$(DEFAULT_DIR)/objects/f64.o: ./source/types/f64/f64.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/f64.d -c ./source/types/f64/f64.c -o $(DEFAULT_DIR)/objects/f64.o

$(DEFAULT_DIR)/objects/f64_to_any.o: ./source/types/f64/f64_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/f64_to_any.d -c ./source/types/f64/f64_to_any.c -o $(DEFAULT_DIR)/objects/f64_to_any.o

$(DEFAULT_DIR)/objects/framework_get.o: ./source/types/framework/framework_get.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/framework_get.d -c ./source/types/framework/framework_get.c -o $(DEFAULT_DIR)/objects/framework_get.o

$(DEFAULT_DIR)/objects/framework_get_map.o: ./source/types/framework/framework_get_map.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/framework_get_map.d -c ./source/types/framework/framework_get_map.c -o $(DEFAULT_DIR)/objects/framework_get_map.o

$(DEFAULT_DIR)/objects/framework_get_memtree.o: ./source/types/framework/framework_get_memtree.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/framework_get_memtree.d -c ./source/types/framework/framework_get_memtree.c -o $(DEFAULT_DIR)/objects/framework_get_memtree.o

$(DEFAULT_DIR)/objects/i32.o: ./source/types/i32/i32.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/i32.d -c ./source/types/i32/i32.c -o $(DEFAULT_DIR)/objects/i32.o

$(DEFAULT_DIR)/objects/i32_to_any.o: ./source/types/i32/i32_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/i32_to_any.d -c ./source/types/i32/i32_to_any.c -o $(DEFAULT_DIR)/objects/i32_to_any.o

$(DEFAULT_DIR)/objects/i64.o: ./source/types/i64/i64.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/i64.d -c ./source/types/i64/i64.c -o $(DEFAULT_DIR)/objects/i64.o

$(DEFAULT_DIR)/objects/i64_is_i32.o: ./source/types/i64/i64_is_i32.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/i64_is_i32.d -c ./source/types/i64/i64_is_i32.c -o $(DEFAULT_DIR)/objects/i64_is_i32.o

$(DEFAULT_DIR)/objects/i64_to_any.o: ./source/types/i64/i64_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/i64_to_any.d -c ./source/types/i64/i64_to_any.c -o $(DEFAULT_DIR)/objects/i64_to_any.o

$(DEFAULT_DIR)/objects/i8.o: ./source/types/i8/i8.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/i8.d -c ./source/types/i8/i8.c -o $(DEFAULT_DIR)/objects/i8.o

$(DEFAULT_DIR)/objects/i8_is_digit.o: ./source/types/i8/i8_is_digit.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/i8_is_digit.d -c ./source/types/i8/i8_is_digit.c -o $(DEFAULT_DIR)/objects/i8_is_digit.o

$(DEFAULT_DIR)/objects/i8_is_signal.o: ./source/types/i8/i8_is_signal.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/i8_is_signal.d -c ./source/types/i8/i8_is_signal.c -o $(DEFAULT_DIR)/objects/i8_is_signal.o

$(DEFAULT_DIR)/objects/i8_is_space.o: ./source/types/i8/i8_is_space.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/i8_is_space.d -c ./source/types/i8/i8_is_space.c -o $(DEFAULT_DIR)/objects/i8_is_space.o

$(DEFAULT_DIR)/objects/i8_sequence.o: ./source/types/i8/i8_sequence.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/i8_sequence.d -c ./source/types/i8/i8_sequence.c -o $(DEFAULT_DIR)/objects/i8_sequence.o

$(DEFAULT_DIR)/objects/i8_sequence_is_i32.o: ./source/types/i8/i8_sequence_is_i32.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/i8_sequence_is_i32.d -c ./source/types/i8/i8_sequence_is_i32.c -o $(DEFAULT_DIR)/objects/i8_sequence_is_i32.o

$(DEFAULT_DIR)/objects/i8_sequence_to_any.o: ./source/types/i8/i8_sequence_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/i8_sequence_to_any.d -c ./source/types/i8/i8_sequence_to_any.c -o $(DEFAULT_DIR)/objects/i8_sequence_to_any.o

$(DEFAULT_DIR)/objects/i8_sequence_to_i32.o: ./source/types/i8/i8_sequence_to_i32.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/i8_sequence_to_i32.d -c ./source/types/i8/i8_sequence_to_i32.c -o $(DEFAULT_DIR)/objects/i8_sequence_to_i32.o

$(DEFAULT_DIR)/objects/i8_to_any.o: ./source/types/i8/i8_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/i8_to_any.d -c ./source/types/i8/i8_to_any.c -o $(DEFAULT_DIR)/objects/i8_to_any.o

$(DEFAULT_DIR)/objects/list.o: ./source/types/list/list.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/list.d -c ./source/types/list/list.c -o $(DEFAULT_DIR)/objects/list.o

$(DEFAULT_DIR)/objects/list_as_any.o: ./source/types/list/list_as_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/list_as_any.d -c ./source/types/list/list_as_any.c -o $(DEFAULT_DIR)/objects/list_as_any.o

$(DEFAULT_DIR)/objects/list_copy.o: ./source/types/list/list_copy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/list_copy.d -c ./source/types/list/list_copy.c -o $(DEFAULT_DIR)/objects/list_copy.o

$(DEFAULT_DIR)/objects/list_create.o: ./source/types/list/list_create.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/list_create.d -c ./source/types/list/list_create.c -o $(DEFAULT_DIR)/objects/list_create.o

$(DEFAULT_DIR)/objects/list_destroy.o: ./source/types/list/list_destroy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/list_destroy.d -c ./source/types/list/list_destroy.c -o $(DEFAULT_DIR)/objects/list_destroy.o

$(DEFAULT_DIR)/objects/list_expand.o: ./source/types/list/list_expand.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/list_expand.d -c ./source/types/list/list_expand.c -o $(DEFAULT_DIR)/objects/list_expand.o

$(DEFAULT_DIR)/objects/list_get.o: ./source/types/list/list_get.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/list_get.d -c ./source/types/list/list_get.c -o $(DEFAULT_DIR)/objects/list_get.o

$(DEFAULT_DIR)/objects/list_get_length.o: ./source/types/list/list_get_length.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/list_get_length.d -c ./source/types/list/list_get_length.c -o $(DEFAULT_DIR)/objects/list_get_length.o

$(DEFAULT_DIR)/objects/list_pop.o: ./source/types/list/list_pop.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/list_pop.d -c ./source/types/list/list_pop.c -o $(DEFAULT_DIR)/objects/list_pop.o

$(DEFAULT_DIR)/objects/list_push.o: ./source/types/list/list_push.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/list_push.d -c ./source/types/list/list_push.c -o $(DEFAULT_DIR)/objects/list_push.o

$(DEFAULT_DIR)/objects/list_reverse.o: ./source/types/list/list_reverse.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/list_reverse.d -c ./source/types/list/list_reverse.c -o $(DEFAULT_DIR)/objects/list_reverse.o

$(DEFAULT_DIR)/objects/list_set.o: ./source/types/list/list_set.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/list_set.d -c ./source/types/list/list_set.c -o $(DEFAULT_DIR)/objects/list_set.o

$(DEFAULT_DIR)/objects/list_shift.o: ./source/types/list/list_shift.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/list_shift.d -c ./source/types/list/list_shift.c -o $(DEFAULT_DIR)/objects/list_shift.o

$(DEFAULT_DIR)/objects/list_unshift.o: ./source/types/list/list_unshift.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/list_unshift.d -c ./source/types/list/list_unshift.c -o $(DEFAULT_DIR)/objects/list_unshift.o

$(DEFAULT_DIR)/objects/map.o: ./source/types/map/map.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/map.d -c ./source/types/map/map.c -o $(DEFAULT_DIR)/objects/map.o

$(DEFAULT_DIR)/objects/map_copy.o: ./source/types/map/map_copy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/map_copy.d -c ./source/types/map/map_copy.c -o $(DEFAULT_DIR)/objects/map_copy.o

$(DEFAULT_DIR)/objects/map_create.o: ./source/types/map/map_create.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/map_create.d -c ./source/types/map/map_create.c -o $(DEFAULT_DIR)/objects/map_create.o

$(DEFAULT_DIR)/objects/map_destroy.o: ./source/types/map/map_destroy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/map_destroy.d -c ./source/types/map/map_destroy.c -o $(DEFAULT_DIR)/objects/map_destroy.o

$(DEFAULT_DIR)/objects/map_expand.o: ./source/types/map/map_expand.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/map_expand.d -c ./source/types/map/map_expand.c -o $(DEFAULT_DIR)/objects/map_expand.o

$(DEFAULT_DIR)/objects/map_get.o: ./source/types/map/map_get.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/map_get.d -c ./source/types/map/map_get.c -o $(DEFAULT_DIR)/objects/map_get.o

$(DEFAULT_DIR)/objects/map_hash.o: ./source/types/map/map_hash.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/map_hash.d -c ./source/types/map/map_hash.c -o $(DEFAULT_DIR)/objects/map_hash.o

$(DEFAULT_DIR)/objects/map_set.o: ./source/types/map/map_set.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/map_set.d -c ./source/types/map/map_set.c -o $(DEFAULT_DIR)/objects/map_set.o

$(DEFAULT_DIR)/objects/memtree_create.o: ./source/types/memtree/memtree_create.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/memtree_create.d -c ./source/types/memtree/memtree_create.c -o $(DEFAULT_DIR)/objects/memtree_create.o

$(DEFAULT_DIR)/objects/memtree_delete.o: ./source/types/memtree/memtree_delete.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/memtree_delete.d -c ./source/types/memtree/memtree_delete.c -o $(DEFAULT_DIR)/objects/memtree_delete.o

$(DEFAULT_DIR)/objects/memtree_destroy.o: ./source/types/memtree/memtree_destroy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/memtree_destroy.d -c ./source/types/memtree/memtree_destroy.c -o $(DEFAULT_DIR)/objects/memtree_destroy.o

$(DEFAULT_DIR)/objects/memtree_get.o: ./source/types/memtree/memtree_get.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/memtree_get.d -c ./source/types/memtree/memtree_get.c -o $(DEFAULT_DIR)/objects/memtree_get.o

$(DEFAULT_DIR)/objects/memtree_get_height.o: ./source/types/memtree/memtree_get_height.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/memtree_get_height.d -c ./source/types/memtree/memtree_get_height.c -o $(DEFAULT_DIR)/objects/memtree_get_height.o

$(DEFAULT_DIR)/objects/memtree_insert.o: ./source/types/memtree/memtree_insert.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/memtree_insert.d -c ./source/types/memtree/memtree_insert.c -o $(DEFAULT_DIR)/objects/memtree_insert.o

$(DEFAULT_DIR)/objects/memtree_print.o: ./source/types/memtree/memtree_print.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/memtree_print.d -c ./source/types/memtree/memtree_print.c -o $(DEFAULT_DIR)/objects/memtree_print.o

$(DEFAULT_DIR)/objects/memtree_rebalance.o: ./source/types/memtree/memtree_rebalance.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/memtree_rebalance.d -c ./source/types/memtree/memtree_rebalance.c -o $(DEFAULT_DIR)/objects/memtree_rebalance.o

$(DEFAULT_DIR)/objects/memtree_search.o: ./source/types/memtree/memtree_search.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/memtree_search.d -c ./source/types/memtree/memtree_search.c -o $(DEFAULT_DIR)/objects/memtree_search.o

$(DEFAULT_DIR)/objects/memtree_update_height.o: ./source/types/memtree/memtree_update_height.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/memtree_update_height.d -c ./source/types/memtree/memtree_update_height.c -o $(DEFAULT_DIR)/objects/memtree_update_height.o

$(DEFAULT_DIR)/objects/u32.o: ./source/types/u32/u32.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/u32.d -c ./source/types/u32/u32.c -o $(DEFAULT_DIR)/objects/u32.o

$(DEFAULT_DIR)/objects/u32_to_any.o: ./source/types/u32/u32_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/u32_to_any.d -c ./source/types/u32/u32_to_any.c -o $(DEFAULT_DIR)/objects/u32_to_any.o

$(DEFAULT_DIR)/objects/u64.o: ./source/types/u64/u64.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/u64.d -c ./source/types/u64/u64.c -o $(DEFAULT_DIR)/objects/u64.o

$(DEFAULT_DIR)/objects/u64_to_any.o: ./source/types/u64/u64_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/u64_to_any.d -c ./source/types/u64/u64_to_any.c -o $(DEFAULT_DIR)/objects/u64_to_any.o

$(DEFAULT_DIR)/objects/u8.o: ./source/types/u8/u8.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/u8.d -c ./source/types/u8/u8.c -o $(DEFAULT_DIR)/objects/u8.o

$(DEFAULT_DIR)/objects/u8_to_any.o: ./source/types/u8/u8_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/u8_to_any.d -c ./source/types/u8/u8_to_any.c -o $(DEFAULT_DIR)/objects/u8_to_any.o


$(DEBUG_DIR)/objects/allocate.o: ./source/functions/allocate.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/allocate.d -c ./source/functions/allocate.c -o $(DEBUG_DIR)/objects/allocate.o

$(DEBUG_DIR)/objects/assert.o: ./source/functions/assert.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/assert.d -c ./source/functions/assert.c -o $(DEBUG_DIR)/objects/assert.o

$(DEBUG_DIR)/objects/as_any.o: ./source/functions/as_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/as_any.d -c ./source/functions/as_any.c -o $(DEBUG_DIR)/objects/as_any.o

$(DEBUG_DIR)/objects/compare.o: ./source/functions/compare.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/compare.d -c ./source/functions/compare.c -o $(DEBUG_DIR)/objects/compare.o

$(DEBUG_DIR)/objects/conceal.o: ./source/functions/conceal.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/conceal.d -c ./source/functions/conceal.c -o $(DEBUG_DIR)/objects/conceal.o

$(DEBUG_DIR)/objects/copy.o: ./source/functions/copy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/copy.d -c ./source/functions/copy.c -o $(DEBUG_DIR)/objects/copy.o

$(DEBUG_DIR)/objects/create.o: ./source/functions/create.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/create.d -c ./source/functions/create.c -o $(DEBUG_DIR)/objects/create.o

$(DEBUG_DIR)/objects/deallocate.o: ./source/functions/deallocate.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/deallocate.d -c ./source/functions/deallocate.c -o $(DEBUG_DIR)/objects/deallocate.o

$(DEBUG_DIR)/objects/debug.o: ./source/functions/debug.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/debug.d -c ./source/functions/debug.c -o $(DEBUG_DIR)/objects/debug.o

$(DEBUG_DIR)/objects/delete.o: ./source/functions/delete.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/delete.d -c ./source/functions/delete.c -o $(DEBUG_DIR)/objects/delete.o

$(DEBUG_DIR)/objects/destroy.o: ./source/functions/destroy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/destroy.d -c ./source/functions/destroy.c -o $(DEBUG_DIR)/objects/destroy.o

$(DEBUG_DIR)/objects/display.o: ./source/functions/display.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/display.d -c ./source/functions/display.c -o $(DEBUG_DIR)/objects/display.o

$(DEBUG_DIR)/objects/error.o: ./source/functions/error.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/error.d -c ./source/functions/error.c -o $(DEBUG_DIR)/objects/error.o

$(DEBUG_DIR)/objects/filter.o: ./source/functions/filter.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/filter.d -c ./source/functions/filter.c -o $(DEBUG_DIR)/objects/filter.o

$(DEBUG_DIR)/objects/find.o: ./source/functions/find.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/find.d -c ./source/functions/find.c -o $(DEBUG_DIR)/objects/find.o

$(DEBUG_DIR)/objects/foreach.o: ./source/functions/foreach.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/foreach.d -c ./source/functions/foreach.c -o $(DEBUG_DIR)/objects/foreach.o

$(DEBUG_DIR)/objects/forkrun.o: ./source/functions/forkrun.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/forkrun.d -c ./source/functions/forkrun.c -o $(DEBUG_DIR)/objects/forkrun.o

$(DEBUG_DIR)/objects/init.o: ./source/functions/init.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/init.d -c ./source/functions/init.c -o $(DEBUG_DIR)/objects/init.o

$(DEBUG_DIR)/objects/new.o: ./source/functions/new.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/new.d -c ./source/functions/new.c -o $(DEBUG_DIR)/objects/new.o

$(DEBUG_DIR)/objects/print.o: ./source/functions/print.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/print.d -c ./source/functions/print.c -o $(DEBUG_DIR)/objects/print.o

$(DEBUG_DIR)/objects/push.o: ./source/functions/push.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/push.d -c ./source/functions/push.c -o $(DEBUG_DIR)/objects/push.o

$(DEBUG_DIR)/objects/quit.o: ./source/functions/quit.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/quit.d -c ./source/functions/quit.c -o $(DEBUG_DIR)/objects/quit.o

$(DEBUG_DIR)/objects/range.o: ./source/functions/range.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/range.d -c ./source/functions/range.c -o $(DEBUG_DIR)/objects/range.o

$(DEBUG_DIR)/objects/reduce.o: ./source/functions/reduce.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/reduce.d -c ./source/functions/reduce.c -o $(DEBUG_DIR)/objects/reduce.o

$(DEBUG_DIR)/objects/repeat.o: ./source/functions/repeat.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/repeat.d -c ./source/functions/repeat.c -o $(DEBUG_DIR)/objects/repeat.o

$(DEBUG_DIR)/objects/retrieve.o: ./source/functions/retrieve.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/retrieve.d -c ./source/functions/retrieve.c -o $(DEBUG_DIR)/objects/retrieve.o

$(DEBUG_DIR)/objects/share.o: ./source/functions/share.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/share.d -c ./source/functions/share.c -o $(DEBUG_DIR)/objects/share.o

$(DEBUG_DIR)/objects/slice.o: ./source/functions/slice.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/slice.d -c ./source/functions/slice.c -o $(DEBUG_DIR)/objects/slice.o

$(DEBUG_DIR)/objects/to_any.o: ./source/functions/to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/to_any.d -c ./source/functions/to_any.c -o $(DEBUG_DIR)/objects/to_any.o

$(DEBUG_DIR)/objects/warning.o: ./source/functions/warning.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/warning.d -c ./source/functions/warning.c -o $(DEBUG_DIR)/objects/warning.o

$(DEBUG_DIR)/objects/any.o: ./source/types/any/any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any.d -c ./source/types/any/any.c -o $(DEBUG_DIR)/objects/any.o

$(DEBUG_DIR)/objects/any_as_f64.o: ./source/types/any/any_as_f64.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any_as_f64.d -c ./source/types/any/any_as_f64.c -o $(DEBUG_DIR)/objects/any_as_f64.o

$(DEBUG_DIR)/objects/any_as_i32.o: ./source/types/any/any_as_i32.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any_as_i32.d -c ./source/types/any/any_as_i32.c -o $(DEBUG_DIR)/objects/any_as_i32.o

$(DEBUG_DIR)/objects/any_as_i64.o: ./source/types/any/any_as_i64.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any_as_i64.d -c ./source/types/any/any_as_i64.c -o $(DEBUG_DIR)/objects/any_as_i64.o

$(DEBUG_DIR)/objects/any_as_i8.o: ./source/types/any/any_as_i8.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any_as_i8.d -c ./source/types/any/any_as_i8.c -o $(DEBUG_DIR)/objects/any_as_i8.o

$(DEBUG_DIR)/objects/any_as_instance.o: ./source/types/any/any_as_instance.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any_as_instance.d -c ./source/types/any/any_as_instance.c -o $(DEBUG_DIR)/objects/any_as_instance.o

$(DEBUG_DIR)/objects/any_as_sequence.o: ./source/types/any/any_as_sequence.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any_as_sequence.d -c ./source/types/any/any_as_sequence.c -o $(DEBUG_DIR)/objects/any_as_sequence.o

$(DEBUG_DIR)/objects/any_as_u32.o: ./source/types/any/any_as_u32.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any_as_u32.d -c ./source/types/any/any_as_u32.c -o $(DEBUG_DIR)/objects/any_as_u32.o

$(DEBUG_DIR)/objects/any_as_u64.o: ./source/types/any/any_as_u64.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any_as_u64.d -c ./source/types/any/any_as_u64.c -o $(DEBUG_DIR)/objects/any_as_u64.o

$(DEBUG_DIR)/objects/any_as_u8.o: ./source/types/any/any_as_u8.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any_as_u8.d -c ./source/types/any/any_as_u8.c -o $(DEBUG_DIR)/objects/any_as_u8.o

$(DEBUG_DIR)/objects/any_copy.o: ./source/types/any/any_copy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any_copy.d -c ./source/types/any/any_copy.c -o $(DEBUG_DIR)/objects/any_copy.o

$(DEBUG_DIR)/objects/any_create.o: ./source/types/any/any_create.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any_create.d -c ./source/types/any/any_create.c -o $(DEBUG_DIR)/objects/any_create.o

$(DEBUG_DIR)/objects/any_destroy.o: ./source/types/any/any_destroy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any_destroy.d -c ./source/types/any/any_destroy.c -o $(DEBUG_DIR)/objects/any_destroy.o

$(DEBUG_DIR)/objects/any_to_f64.o: ./source/types/any/any_to_f64.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any_to_f64.d -c ./source/types/any/any_to_f64.c -o $(DEBUG_DIR)/objects/any_to_f64.o

$(DEBUG_DIR)/objects/any_to_i32.o: ./source/types/any/any_to_i32.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any_to_i32.d -c ./source/types/any/any_to_i32.c -o $(DEBUG_DIR)/objects/any_to_i32.o

$(DEBUG_DIR)/objects/any_to_i64.o: ./source/types/any/any_to_i64.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any_to_i64.d -c ./source/types/any/any_to_i64.c -o $(DEBUG_DIR)/objects/any_to_i64.o

$(DEBUG_DIR)/objects/any_to_i8.o: ./source/types/any/any_to_i8.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any_to_i8.d -c ./source/types/any/any_to_i8.c -o $(DEBUG_DIR)/objects/any_to_i8.o

$(DEBUG_DIR)/objects/any_to_instance.o: ./source/types/any/any_to_instance.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any_to_instance.d -c ./source/types/any/any_to_instance.c -o $(DEBUG_DIR)/objects/any_to_instance.o

$(DEBUG_DIR)/objects/any_to_sequence.o: ./source/types/any/any_to_sequence.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any_to_sequence.d -c ./source/types/any/any_to_sequence.c -o $(DEBUG_DIR)/objects/any_to_sequence.o

$(DEBUG_DIR)/objects/any_to_u32.o: ./source/types/any/any_to_u32.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any_to_u32.d -c ./source/types/any/any_to_u32.c -o $(DEBUG_DIR)/objects/any_to_u32.o

$(DEBUG_DIR)/objects/any_to_u64.o: ./source/types/any/any_to_u64.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any_to_u64.d -c ./source/types/any/any_to_u64.c -o $(DEBUG_DIR)/objects/any_to_u64.o

$(DEBUG_DIR)/objects/any_to_u8.o: ./source/types/any/any_to_u8.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any_to_u8.d -c ./source/types/any/any_to_u8.c -o $(DEBUG_DIR)/objects/any_to_u8.o

$(DEBUG_DIR)/objects/f64.o: ./source/types/f64/f64.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/f64.d -c ./source/types/f64/f64.c -o $(DEBUG_DIR)/objects/f64.o

$(DEBUG_DIR)/objects/f64_to_any.o: ./source/types/f64/f64_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/f64_to_any.d -c ./source/types/f64/f64_to_any.c -o $(DEBUG_DIR)/objects/f64_to_any.o

$(DEBUG_DIR)/objects/framework_get.o: ./source/types/framework/framework_get.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/framework_get.d -c ./source/types/framework/framework_get.c -o $(DEBUG_DIR)/objects/framework_get.o

$(DEBUG_DIR)/objects/framework_get_map.o: ./source/types/framework/framework_get_map.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/framework_get_map.d -c ./source/types/framework/framework_get_map.c -o $(DEBUG_DIR)/objects/framework_get_map.o

$(DEBUG_DIR)/objects/framework_get_memtree.o: ./source/types/framework/framework_get_memtree.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/framework_get_memtree.d -c ./source/types/framework/framework_get_memtree.c -o $(DEBUG_DIR)/objects/framework_get_memtree.o

$(DEBUG_DIR)/objects/i32.o: ./source/types/i32/i32.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/i32.d -c ./source/types/i32/i32.c -o $(DEBUG_DIR)/objects/i32.o

$(DEBUG_DIR)/objects/i32_to_any.o: ./source/types/i32/i32_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/i32_to_any.d -c ./source/types/i32/i32_to_any.c -o $(DEBUG_DIR)/objects/i32_to_any.o

$(DEBUG_DIR)/objects/i64.o: ./source/types/i64/i64.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/i64.d -c ./source/types/i64/i64.c -o $(DEBUG_DIR)/objects/i64.o

$(DEBUG_DIR)/objects/i64_is_i32.o: ./source/types/i64/i64_is_i32.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/i64_is_i32.d -c ./source/types/i64/i64_is_i32.c -o $(DEBUG_DIR)/objects/i64_is_i32.o

$(DEBUG_DIR)/objects/i64_to_any.o: ./source/types/i64/i64_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/i64_to_any.d -c ./source/types/i64/i64_to_any.c -o $(DEBUG_DIR)/objects/i64_to_any.o

$(DEBUG_DIR)/objects/i8.o: ./source/types/i8/i8.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/i8.d -c ./source/types/i8/i8.c -o $(DEBUG_DIR)/objects/i8.o

$(DEBUG_DIR)/objects/i8_is_digit.o: ./source/types/i8/i8_is_digit.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/i8_is_digit.d -c ./source/types/i8/i8_is_digit.c -o $(DEBUG_DIR)/objects/i8_is_digit.o

$(DEBUG_DIR)/objects/i8_is_signal.o: ./source/types/i8/i8_is_signal.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/i8_is_signal.d -c ./source/types/i8/i8_is_signal.c -o $(DEBUG_DIR)/objects/i8_is_signal.o

$(DEBUG_DIR)/objects/i8_is_space.o: ./source/types/i8/i8_is_space.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/i8_is_space.d -c ./source/types/i8/i8_is_space.c -o $(DEBUG_DIR)/objects/i8_is_space.o

$(DEBUG_DIR)/objects/i8_sequence.o: ./source/types/i8/i8_sequence.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/i8_sequence.d -c ./source/types/i8/i8_sequence.c -o $(DEBUG_DIR)/objects/i8_sequence.o

$(DEBUG_DIR)/objects/i8_sequence_is_i32.o: ./source/types/i8/i8_sequence_is_i32.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/i8_sequence_is_i32.d -c ./source/types/i8/i8_sequence_is_i32.c -o $(DEBUG_DIR)/objects/i8_sequence_is_i32.o

$(DEBUG_DIR)/objects/i8_sequence_to_any.o: ./source/types/i8/i8_sequence_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/i8_sequence_to_any.d -c ./source/types/i8/i8_sequence_to_any.c -o $(DEBUG_DIR)/objects/i8_sequence_to_any.o

$(DEBUG_DIR)/objects/i8_sequence_to_i32.o: ./source/types/i8/i8_sequence_to_i32.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/i8_sequence_to_i32.d -c ./source/types/i8/i8_sequence_to_i32.c -o $(DEBUG_DIR)/objects/i8_sequence_to_i32.o

$(DEBUG_DIR)/objects/i8_to_any.o: ./source/types/i8/i8_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/i8_to_any.d -c ./source/types/i8/i8_to_any.c -o $(DEBUG_DIR)/objects/i8_to_any.o

$(DEBUG_DIR)/objects/list.o: ./source/types/list/list.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/list.d -c ./source/types/list/list.c -o $(DEBUG_DIR)/objects/list.o

$(DEBUG_DIR)/objects/list_as_any.o: ./source/types/list/list_as_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/list_as_any.d -c ./source/types/list/list_as_any.c -o $(DEBUG_DIR)/objects/list_as_any.o

$(DEBUG_DIR)/objects/list_copy.o: ./source/types/list/list_copy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/list_copy.d -c ./source/types/list/list_copy.c -o $(DEBUG_DIR)/objects/list_copy.o

$(DEBUG_DIR)/objects/list_create.o: ./source/types/list/list_create.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/list_create.d -c ./source/types/list/list_create.c -o $(DEBUG_DIR)/objects/list_create.o

$(DEBUG_DIR)/objects/list_destroy.o: ./source/types/list/list_destroy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/list_destroy.d -c ./source/types/list/list_destroy.c -o $(DEBUG_DIR)/objects/list_destroy.o

$(DEBUG_DIR)/objects/list_expand.o: ./source/types/list/list_expand.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/list_expand.d -c ./source/types/list/list_expand.c -o $(DEBUG_DIR)/objects/list_expand.o

$(DEBUG_DIR)/objects/list_get.o: ./source/types/list/list_get.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/list_get.d -c ./source/types/list/list_get.c -o $(DEBUG_DIR)/objects/list_get.o

$(DEBUG_DIR)/objects/list_get_length.o: ./source/types/list/list_get_length.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/list_get_length.d -c ./source/types/list/list_get_length.c -o $(DEBUG_DIR)/objects/list_get_length.o

$(DEBUG_DIR)/objects/list_pop.o: ./source/types/list/list_pop.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/list_pop.d -c ./source/types/list/list_pop.c -o $(DEBUG_DIR)/objects/list_pop.o

$(DEBUG_DIR)/objects/list_push.o: ./source/types/list/list_push.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/list_push.d -c ./source/types/list/list_push.c -o $(DEBUG_DIR)/objects/list_push.o

$(DEBUG_DIR)/objects/list_reverse.o: ./source/types/list/list_reverse.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/list_reverse.d -c ./source/types/list/list_reverse.c -o $(DEBUG_DIR)/objects/list_reverse.o

$(DEBUG_DIR)/objects/list_set.o: ./source/types/list/list_set.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/list_set.d -c ./source/types/list/list_set.c -o $(DEBUG_DIR)/objects/list_set.o

$(DEBUG_DIR)/objects/list_shift.o: ./source/types/list/list_shift.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/list_shift.d -c ./source/types/list/list_shift.c -o $(DEBUG_DIR)/objects/list_shift.o

$(DEBUG_DIR)/objects/list_unshift.o: ./source/types/list/list_unshift.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/list_unshift.d -c ./source/types/list/list_unshift.c -o $(DEBUG_DIR)/objects/list_unshift.o

$(DEBUG_DIR)/objects/map.o: ./source/types/map/map.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/map.d -c ./source/types/map/map.c -o $(DEBUG_DIR)/objects/map.o

$(DEBUG_DIR)/objects/map_copy.o: ./source/types/map/map_copy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/map_copy.d -c ./source/types/map/map_copy.c -o $(DEBUG_DIR)/objects/map_copy.o

$(DEBUG_DIR)/objects/map_create.o: ./source/types/map/map_create.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/map_create.d -c ./source/types/map/map_create.c -o $(DEBUG_DIR)/objects/map_create.o

$(DEBUG_DIR)/objects/map_destroy.o: ./source/types/map/map_destroy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/map_destroy.d -c ./source/types/map/map_destroy.c -o $(DEBUG_DIR)/objects/map_destroy.o

$(DEBUG_DIR)/objects/map_expand.o: ./source/types/map/map_expand.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/map_expand.d -c ./source/types/map/map_expand.c -o $(DEBUG_DIR)/objects/map_expand.o

$(DEBUG_DIR)/objects/map_get.o: ./source/types/map/map_get.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/map_get.d -c ./source/types/map/map_get.c -o $(DEBUG_DIR)/objects/map_get.o

$(DEBUG_DIR)/objects/map_hash.o: ./source/types/map/map_hash.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/map_hash.d -c ./source/types/map/map_hash.c -o $(DEBUG_DIR)/objects/map_hash.o

$(DEBUG_DIR)/objects/map_set.o: ./source/types/map/map_set.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/map_set.d -c ./source/types/map/map_set.c -o $(DEBUG_DIR)/objects/map_set.o

$(DEBUG_DIR)/objects/memtree_create.o: ./source/types/memtree/memtree_create.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/memtree_create.d -c ./source/types/memtree/memtree_create.c -o $(DEBUG_DIR)/objects/memtree_create.o

$(DEBUG_DIR)/objects/memtree_delete.o: ./source/types/memtree/memtree_delete.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/memtree_delete.d -c ./source/types/memtree/memtree_delete.c -o $(DEBUG_DIR)/objects/memtree_delete.o

$(DEBUG_DIR)/objects/memtree_destroy.o: ./source/types/memtree/memtree_destroy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/memtree_destroy.d -c ./source/types/memtree/memtree_destroy.c -o $(DEBUG_DIR)/objects/memtree_destroy.o

$(DEBUG_DIR)/objects/memtree_get.o: ./source/types/memtree/memtree_get.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/memtree_get.d -c ./source/types/memtree/memtree_get.c -o $(DEBUG_DIR)/objects/memtree_get.o

$(DEBUG_DIR)/objects/memtree_get_height.o: ./source/types/memtree/memtree_get_height.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/memtree_get_height.d -c ./source/types/memtree/memtree_get_height.c -o $(DEBUG_DIR)/objects/memtree_get_height.o

$(DEBUG_DIR)/objects/memtree_insert.o: ./source/types/memtree/memtree_insert.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/memtree_insert.d -c ./source/types/memtree/memtree_insert.c -o $(DEBUG_DIR)/objects/memtree_insert.o

$(DEBUG_DIR)/objects/memtree_print.o: ./source/types/memtree/memtree_print.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/memtree_print.d -c ./source/types/memtree/memtree_print.c -o $(DEBUG_DIR)/objects/memtree_print.o

$(DEBUG_DIR)/objects/memtree_rebalance.o: ./source/types/memtree/memtree_rebalance.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/memtree_rebalance.d -c ./source/types/memtree/memtree_rebalance.c -o $(DEBUG_DIR)/objects/memtree_rebalance.o

$(DEBUG_DIR)/objects/memtree_search.o: ./source/types/memtree/memtree_search.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/memtree_search.d -c ./source/types/memtree/memtree_search.c -o $(DEBUG_DIR)/objects/memtree_search.o

$(DEBUG_DIR)/objects/memtree_update_height.o: ./source/types/memtree/memtree_update_height.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/memtree_update_height.d -c ./source/types/memtree/memtree_update_height.c -o $(DEBUG_DIR)/objects/memtree_update_height.o

$(DEBUG_DIR)/objects/u32.o: ./source/types/u32/u32.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/u32.d -c ./source/types/u32/u32.c -o $(DEBUG_DIR)/objects/u32.o

$(DEBUG_DIR)/objects/u32_to_any.o: ./source/types/u32/u32_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/u32_to_any.d -c ./source/types/u32/u32_to_any.c -o $(DEBUG_DIR)/objects/u32_to_any.o

$(DEBUG_DIR)/objects/u64.o: ./source/types/u64/u64.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/u64.d -c ./source/types/u64/u64.c -o $(DEBUG_DIR)/objects/u64.o

$(DEBUG_DIR)/objects/u64_to_any.o: ./source/types/u64/u64_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/u64_to_any.d -c ./source/types/u64/u64_to_any.c -o $(DEBUG_DIR)/objects/u64_to_any.o

$(DEBUG_DIR)/objects/u8.o: ./source/types/u8/u8.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/u8.d -c ./source/types/u8/u8.c -o $(DEBUG_DIR)/objects/u8.o

$(DEBUG_DIR)/objects/u8_to_any.o: ./source/types/u8/u8_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/u8_to_any.d -c ./source/types/u8/u8_to_any.c -o $(DEBUG_DIR)/objects/u8_to_any.o


$(TESTS_DIR)/objects/allocate.o: ./tests/functions/allocate.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(TESTS_DIR)/dependencies/allocate.d -c ./tests/functions/allocate.c -o $(TESTS_DIR)/objects/allocate.o
	@$(CC) $(CFLAGS) $(CPATHS) $(TESTS_DIR)/objects/allocate.o $(DEFAULT) -o $(TESTS_DIR)/bin/allocate

$(TESTS_DIR)/objects/assert.o: ./tests/functions/assert.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(TESTS_DIR)/dependencies/assert.d -c ./tests/functions/assert.c -o $(TESTS_DIR)/objects/assert.o
	@$(CC) $(CFLAGS) $(CPATHS) $(TESTS_DIR)/objects/assert.o $(DEFAULT) -o $(TESTS_DIR)/bin/assert

$(TESTS_DIR)/objects/deallocate.o: ./tests/functions/deallocate.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(TESTS_DIR)/dependencies/deallocate.d -c ./tests/functions/deallocate.c -o $(TESTS_DIR)/objects/deallocate.o
	@$(CC) $(CFLAGS) $(CPATHS) $(TESTS_DIR)/objects/deallocate.o $(DEFAULT) -o $(TESTS_DIR)/bin/deallocate

$(TESTS_DIR)/objects/debug.o: ./tests/functions/debug.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(TESTS_DIR)/dependencies/debug.d -c ./tests/functions/debug.c -o $(TESTS_DIR)/objects/debug.o
	@$(CC) $(CFLAGS) $(CPATHS) $(TESTS_DIR)/objects/debug.o $(DEFAULT) -o $(TESTS_DIR)/bin/debug

$(TESTS_DIR)/objects/delete.o: ./tests/functions/delete.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(TESTS_DIR)/dependencies/delete.d -c ./tests/functions/delete.c -o $(TESTS_DIR)/objects/delete.o
	@$(CC) $(CFLAGS) $(CPATHS) $(TESTS_DIR)/objects/delete.o $(DEFAULT) -o $(TESTS_DIR)/bin/delete

$(TESTS_DIR)/objects/display.o: ./tests/functions/display.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(TESTS_DIR)/dependencies/display.d -c ./tests/functions/display.c -o $(TESTS_DIR)/objects/display.o
	@$(CC) $(CFLAGS) $(CPATHS) $(TESTS_DIR)/objects/display.o $(DEFAULT) -o $(TESTS_DIR)/bin/display

$(TESTS_DIR)/objects/error.o: ./tests/functions/error.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(TESTS_DIR)/dependencies/error.d -c ./tests/functions/error.c -o $(TESTS_DIR)/objects/error.o
	@$(CC) $(CFLAGS) $(CPATHS) $(TESTS_DIR)/objects/error.o $(DEFAULT) -o $(TESTS_DIR)/bin/error

$(TESTS_DIR)/objects/forkrun.o: ./tests/functions/forkrun.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(TESTS_DIR)/dependencies/forkrun.d -c ./tests/functions/forkrun.c -o $(TESTS_DIR)/objects/forkrun.o
	@$(CC) $(CFLAGS) $(CPATHS) $(TESTS_DIR)/objects/forkrun.o $(DEFAULT) -o $(TESTS_DIR)/bin/forkrun

$(TESTS_DIR)/objects/new.o: ./tests/functions/new.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(TESTS_DIR)/dependencies/new.d -c ./tests/functions/new.c -o $(TESTS_DIR)/objects/new.o
	@$(CC) $(CFLAGS) $(CPATHS) $(TESTS_DIR)/objects/new.o $(DEFAULT) -o $(TESTS_DIR)/bin/new

$(TESTS_DIR)/objects/repeat.o: ./tests/functions/repeat.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(TESTS_DIR)/dependencies/repeat.d -c ./tests/functions/repeat.c -o $(TESTS_DIR)/objects/repeat.o
	@$(CC) $(CFLAGS) $(CPATHS) $(TESTS_DIR)/objects/repeat.o $(DEFAULT) -o $(TESTS_DIR)/bin/repeat

$(TESTS_DIR)/objects/warning.o: ./tests/functions/warning.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(TESTS_DIR)/dependencies/warning.d -c ./tests/functions/warning.c -o $(TESTS_DIR)/objects/warning.o
	@$(CC) $(CFLAGS) $(CPATHS) $(TESTS_DIR)/objects/warning.o $(DEFAULT) -o $(TESTS_DIR)/bin/warning

$(TESTS_DIR)/objects/any.o: ./tests/types/any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(TESTS_DIR)/dependencies/any.d -c ./tests/types/any.c -o $(TESTS_DIR)/objects/any.o
	@$(CC) $(CFLAGS) $(CPATHS) $(TESTS_DIR)/objects/any.o $(DEFAULT) -o $(TESTS_DIR)/bin/any

$(TESTS_DIR)/objects/framework.o: ./tests/types/framework.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(TESTS_DIR)/dependencies/framework.d -c ./tests/types/framework.c -o $(TESTS_DIR)/objects/framework.o
	@$(CC) $(CFLAGS) $(CPATHS) $(TESTS_DIR)/objects/framework.o $(DEFAULT) -o $(TESTS_DIR)/bin/framework

$(TESTS_DIR)/objects/map.o: ./tests/types/map.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(TESTS_DIR)/dependencies/map.d -c ./tests/types/map.c -o $(TESTS_DIR)/objects/map.o
	@$(CC) $(CFLAGS) $(CPATHS) $(TESTS_DIR)/objects/map.o $(DEFAULT) -o $(TESTS_DIR)/bin/map

$(TESTS_DIR)/objects/memtree.o: ./tests/types/memtree.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(TESTS_DIR)/dependencies/memtree.d -c ./tests/types/memtree.c -o $(TESTS_DIR)/objects/memtree.o
	@$(CC) $(CFLAGS) $(CPATHS) $(TESTS_DIR)/objects/memtree.o $(DEFAULT) -o $(TESTS_DIR)/bin/memtree

$(TESTS_DIR)/objects/string.o: ./tests/types/string.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(TESTS_DIR)/dependencies/string.d -c ./tests/types/string.c -o $(TESTS_DIR)/objects/string.o
	@$(CC) $(CFLAGS) $(CPATHS) $(TESTS_DIR)/objects/string.o $(DEFAULT) -o $(TESTS_DIR)/bin/string

$(TESTS_DIR)/objects/type.o: ./tests/types/type.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(TESTS_DIR)/dependencies/type.d -c ./tests/types/type.c -o $(TESTS_DIR)/objects/type.o
	@$(CC) $(CFLAGS) $(CPATHS) $(TESTS_DIR)/objects/type.o $(DEFAULT) -o $(TESTS_DIR)/bin/type


