#!/bin/bash

# Cursor Movement
CURSOR_UP='\e[2A'
CURSOR_DOWN='\e[2B'
CURSOR_FORWARD='\e[2C'
CURSOR_BACKWARD='\e[2D'
CURSOR_BEGINNING_LINE='\r'
CURSOR_TO_COORDINATE='\e[<row>;<column>H'

# Clearing the Screen
CLEAR_SCREEN='\e[2J'
CLEAR_TO_END_SCREEN='\e[0J'
CLEAR_TO_BEGINNING_SCREEN='\e[1J'
CLEAR_LINE='\e[2K'
CLEAR_TO_END_LINE='\e[0K'
CLEAR_TO_BEGINNING_LINE='\e[1K'

# Cursor Visibility
HIDE_CURSOR='\e[?25l'
SHOW_CURSOR='\e[?25h'

# Cursor Position
SAVE_CURSOR_POSITION='\e[s'
RESTORE_CURSOR_POSITION='\e[u'
